// SPDX-License-Identifier: Apache-2.0
// Generate per-module DPI probes for generated full-checkpoint RTL modules.

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

struct SignalSpec {
  std::string name;
  std::string width;
  std::string description;
};

struct CycleStep {
  int cycle;
  std::string phase;
  std::string responsibility;
  std::string observed_signals;
  std::string dpi_check;
};

struct ModuleSpec {
  std::string name;
  std::string top_module;
  std::string probe_module;
  std::vector<std::string> rtl;
  std::vector<std::string> cycle_notes;
  std::vector<SignalSpec> input_signals;
  std::vector<SignalSpec> output_signals;
  std::string probe_sv;
};

const std::vector<std::string>& known_child_modules() {
  static const std::vector<std::string> modules = {
      "e1_h1_tinyllama_linear_scheduler",
      "e1_h1_tinyllama_linear_tile_engine",
      "e1_h1_tinyllama_control_scheduler",
      "e1_h1_tinyllama_graph_sequencer",
      "e1_h1_tinyllama_linear_slot_engine",
      "e1_h1_tinyllama_control_slot_engine",
      "e1_h1_tinyllama_full_checkpoint_top",
      "e1_h1_stream_sram",
      "e1_h1_systolic_array",
  };
  return modules;
}

std::vector<std::string> allowed_child_modules(const ModuleSpec& spec) {
  if (spec.name == "linear_tile_engine") {
    return {
        "e1_h1_tinyllama_linear_scheduler",
        "e1_h1_stream_sram",
        "e1_h1_systolic_array",
    };
  }
  if (spec.name == "linear_slot_engine") {
    return {
        "e1_h1_stream_sram",
        "e1_h1_systolic_array",
    };
  }
  if (spec.name == "full_checkpoint_top") {
    return {
        "e1_h1_tinyllama_graph_sequencer",
        "e1_h1_tinyllama_linear_slot_engine",
        "e1_h1_tinyllama_control_slot_engine",
    };
  }
  return {};
}

std::vector<std::string> forbidden_child_modules(const ModuleSpec& spec) {
  const std::vector<std::string> allowed = allowed_child_modules(spec);
  std::vector<std::string> forbidden;
  for (const std::string& module : known_child_modules()) {
    if (module == spec.top_module) {
      continue;
    }
    bool is_allowed = false;
    for (const std::string& child : allowed) {
      if (child == module) {
        is_allowed = true;
      }
    }
    if (!is_allowed) {
      forbidden.push_back(module);
    }
  }
  return forbidden;
}

std::string read_text(const fs::path& path) {
  std::ifstream input(path);
  if (!input) {
    throw std::runtime_error("cannot read " + path.string());
  }
  std::ostringstream buffer;
  buffer << input.rdbuf();
  return buffer.str();
}

void write_text(const fs::path& path, const std::string& text) {
  fs::create_directories(path.parent_path());
  std::ofstream output(path);
  if (!output) {
    throw std::runtime_error("cannot write " + path.string());
  }
  output << text;
}

void validate_rtl_inputs(const fs::path& repo_root, const ModuleSpec& spec) {
  for (const std::string& rtl : spec.rtl) {
    const fs::path rtl_path = repo_root / rtl;
    const std::string text = read_text(rtl_path);
    if (text.find("module " + spec.top_module) == std::string::npos &&
        rtl == spec.rtl.back()) {
      throw std::runtime_error(rtl + " does not define " + spec.top_module);
    }
  }
}

void validate_isolation(const fs::path& repo_root, const ModuleSpec& spec) {
  const std::string dut_text = read_text(repo_root / spec.rtl.back());
  for (const std::string& child : allowed_child_modules(spec)) {
    if (dut_text.find(child) == std::string::npos) {
      throw std::runtime_error(spec.name + " is missing allowed child " + child);
    }
  }
  for (const std::string& child : forbidden_child_modules(spec)) {
    if (dut_text.find(child) != std::string::npos) {
      throw std::runtime_error(spec.name + " unexpectedly references forbidden child " + child);
    }
  }
}

std::string scoreboard_cpp() {
  return R"cpp(// SPDX-License-Identifier: Apache-2.0
// Generated by e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp.

#include <cstdio>

extern "C" void e1_h1_full_dpi_begin(const char* module_name, const char* vip_case) {
  std::printf("E1_H1_FULL_MODULE_DPI_BEGIN module=%s case=%s\n", module_name, vip_case);
}

extern "C" void e1_h1_full_dpi_cycle(const char* module_name, int cycle, const char* phase) {
  if (cycle < 4 || (cycle % 256) == 0) {
    std::printf("E1_H1_FULL_MODULE_DPI_CYCLE module=%s cycle=%d phase=%s\n", module_name, cycle, phase);
  }
}

extern "C" int e1_h1_full_dpi_expect_u32(
    const char* module_name,
    const char* signal_name,
    int cycle,
    int expected,
    int actual) {
  if (expected != actual) {
    std::fprintf(
        stderr,
        "E1_H1_FULL_MODULE_DPI_MISMATCH module=%s signal=%s cycle=%d expected=0x%x actual=0x%x\n",
        module_name,
        signal_name,
        cycle,
        static_cast<unsigned>(expected),
        static_cast<unsigned>(actual));
    return 0;
  }
  return 1;
}
)cpp";
}

std::string main_cpp(const ModuleSpec& spec) {
  std::ostringstream out;
  out << "// SPDX-License-Identifier: Apache-2.0\n";
  out << "// Generated by e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp.\n\n";
  out << "#include \"V" << spec.probe_module << ".h\"\n";
  out << "#include \"verilated.h\"\n\n";
  out << "int main(int argc, char** argv) {\n";
  out << "  VerilatedContext context;\n";
  out << "  context.commandArgs(argc, argv);\n";
  out << "  V" << spec.probe_module << " top{&context};\n";
  out << "  while (!context.gotFinish() && context.time() < 200000) {\n";
  out << "    top.eval();\n";
  out << "    context.timeInc(1);\n";
  out << "  }\n";
  out << "  return context.gotFinish() ? 0 : 1;\n";
  out << "}\n";
  return out.str();
}

std::string flist_text(const fs::path& probe, const ModuleSpec& spec) {
  std::ostringstream out;
  for (const std::string& rtl : spec.rtl) {
    out << rtl << "\n";
  }
  out << probe.generic_string() << "\n";
  return out.str();
}

void write_signal_array_json(std::ostringstream& out,
                             const std::string& key,
                             const std::vector<SignalSpec>& signals,
                             const std::string& indent) {
  out << indent << "\"" << key << "\": [";
  if (!signals.empty()) {
    out << "\n";
  }
  for (std::size_t i = 0; i < signals.size(); ++i) {
    const SignalSpec& signal = signals[i];
    out << indent << "  {\"name\": \"" << signal.name << "\", \"width\": \"" << signal.width
        << "\", \"description\": \"" << signal.description << "\"}"
        << (i + 1 == signals.size() ? "\n" : ",\n");
  }
  out << indent << "]";
}

void write_string_array_json(std::ostringstream& out,
                             const std::string& key,
                             const std::vector<std::string>& values,
                             const std::string& indent) {
  out << indent << "\"" << key << "\": [";
  for (std::size_t i = 0; i < values.size(); ++i) {
    out << (i == 0 ? "" : ", ") << "\"" << values[i] << "\"";
  }
  out << "]";
}

std::vector<std::string> cycle_phase_signals(const ModuleSpec& spec) {
  std::vector<std::string> signals;
  for (const SignalSpec& signal : spec.output_signals) {
    if (signal.name.find("cycle_phase") != std::string::npos) {
      signals.push_back(signal.name);
    }
  }
  return signals;
}

std::string cycle_template_name(const ModuleSpec& spec) {
  if (spec.name == "linear_scheduler" || spec.name == "linear_tile_engine" ||
      spec.name == "linear_slot_engine") {
    return "tile_command_8_cycle_cpu_latch_array_template";
  }
  if (spec.name == "control_scheduler" || spec.name == "control_slot_engine") {
    return "control_op_4_cycle_cpu_template";
  }
  if (spec.name == "graph_sequencer") {
    return "graph_slot_4_cycle_launch_template";
  }
  if (spec.name == "full_checkpoint_top") {
    return "top_dispatch_4_cycle_slot_engine_template";
  }
  throw std::runtime_error("no cycle template for " + spec.name);
}

std::vector<CycleStep> cycle_steps(const ModuleSpec& spec) {
  if (spec.name == "linear_scheduler") {
    return {
        {0, "setup_tile_command", "Select the next TinyLlama linear tile command.",
         "cycle_phase_o, layer_o, op_index_o, input_tile_o, output_tile_o",
         "DPI records the phase and later checks issued_commands_o."},
        {1, "assert_scheduler_valid", "Present cmd_valid_o and hold the payload stable.",
         "cycle_phase_o, cmd_valid_o, cmd_*_o", "DPI records the valid phase."},
        {2, "accept_command_handshake", "Accept the command when cmd_ready_i is high.",
         "cycle_phase_o, cmd_valid_o, cmd_ready_i", "DPI records the handshake phase."},
        {3, "wait_for_array_progress_0", "Wait for the first array progress beat.",
         "cycle_phase_o, array_done_i", "DPI records the in-flight phase."},
        {4, "wait_for_array_progress_1", "Wait for the second array progress beat.",
         "cycle_phase_o, array_done_i", "DPI records the in-flight phase."},
        {5, "wait_for_array_progress_2", "Wait for the third array progress beat.",
         "cycle_phase_o, array_done_i", "DPI records the in-flight phase."},
        {6, "sample_array_done", "Sample array_done_i or array_error_i for the command.",
         "cycle_phase_o, array_done_i, array_error_i", "DPI drives array_done_i in this phase."},
        {7, "advance_tile_counters", "Advance layer/op/tile counters for the next command.",
         "cycle_phase_o, issued_commands_o", "DPI checks the accepted command count."},
    };
  }
  if (spec.name == "linear_tile_engine") {
    return {
        {0, "setup_tile_engine", "Start the scheduler/latch/array composition.",
         "cycle_phase_o, scheduler_cmd_valid_o", "DPI records the composed engine phase."},
        {1, "scheduler_valid_visible", "Expose the ungated scheduler command-valid.",
         "cycle_phase_o, scheduler_cmd_valid_o", "DPI records valid before array valid."},
        {2, "array_command_handshake", "Gate the command into the systolic array.",
         "cycle_phase_o, array_cmd_valid_o, array_cmd_ready_o", "DPI observes the array handshake."},
        {3, "latch_to_array_beat_0", "Present the first latched stream beat to the array.",
         "cycle_phase_o, buffer_array_valid_o, buffer_array_data_o", "DPI records latch output."},
        {4, "latch_to_array_beat_1", "Stage or forward the next stream beat.",
         "cycle_phase_o, buffer_array_valid_o, buffer_array_ready_o", "DPI records latch readiness."},
        {5, "latch_to_array_beat_2", "Continue array input transfer.",
         "cycle_phase_o, buffer_array_valid_o, buffer_array_ready_o", "DPI records latch transfer."},
        {6, "array_done_pulse", "Observe the systolic-array completion pulse.",
         "cycle_phase_o, array_done_o, array_debug_busy_o", "DPI checks completion progress."},
        {7, "return_ready", "Return the composition to ready for the next tile.",
         "cycle_phase_o, issued_commands_o", "DPI checks issued command progress."},
    };
  }
  if (spec.name == "control_scheduler") {
    return {
        {0, "issue_control_op", "Present the current non-linear control op.",
         "cycle_phase_o, control_valid_o, layer_o, layer_op_slot_o", "DPI records issue."},
        {1, "read_control_metadata", "Read source/control metadata for the op.",
         "cycle_phase_o, control_kind_o", "DPI records metadata phase."},
        {2, "execute_control_op", "Execute the CPU/control operation.",
         "cycle_phase_o, control_ready_i", "DPI records execute phase."},
        {3, "commit_control_op", "Commit the op and advance counters.",
         "cycle_phase_o, control_commit_o, issued_control_ops_o", "DPI checks committed count."},
    };
  }
  if (spec.name == "graph_sequencer") {
    return {
        {0, "present_graph_slot", "Present the ordered TinyLlama layer graph slot.",
         "cycle_phase_o, slot_valid_o, layer_o, layer_slot_o", "DPI records slot issue."},
        {1, "launch_selected_engine", "Launch either the control or linear slot engine.",
         "cycle_phase_o, launch_control_o, launch_linear_o", "DPI counts launch pulses."},
        {2, "wait_for_slot_done", "Wait for the selected slot engine to complete.",
         "cycle_phase_o, op_done_i", "DPI drives op_done_i in this phase."},
        {3, "commit_graph_slot", "Commit the graph slot and advance layer/slot counters.",
         "cycle_phase_o, issued_graph_slots_o", "DPI checks committed slot count."},
    };
  }
  if (spec.name == "linear_slot_engine") {
    return {
        {0, "latch_selected_linear_slot", "Latch graph-selected layer and linear op.",
         "cycle_phase_o, layer_o, op_index_o", "DPI records selected slot."},
        {1, "slot_command_valid", "Expose the slot-local scheduler command-valid.",
         "cycle_phase_o, scheduler_cmd_valid_o", "DPI records scheduler valid."},
        {2, "array_command_handshake", "Gate the slot command into the systolic array.",
         "cycle_phase_o, array_cmd_valid_o, array_cmd_ready_o", "DPI observes the array handshake."},
        {3, "latch_to_array_beat_0", "Present the first latched stream beat to the array.",
         "cycle_phase_o, buffer_array_valid_o, buffer_array_data_o", "DPI records latch output."},
        {4, "latch_to_array_beat_1", "Stage or forward the next stream beat.",
         "cycle_phase_o, buffer_array_valid_o, buffer_array_ready_o", "DPI records latch readiness."},
        {5, "latch_to_array_beat_2", "Continue array input transfer.",
         "cycle_phase_o, buffer_array_valid_o, buffer_array_ready_o", "DPI records latch transfer."},
        {6, "array_done_pulse", "Observe the systolic-array completion pulse.",
         "cycle_phase_o, array_done_o, array_debug_busy_o", "DPI checks completion progress."},
        {7, "slot_done_or_next_tile", "Finish the slot or advance to its next tile.",
         "cycle_phase_o, issued_commands_o, expected_commands_o", "DPI checks bounded command count."},
    };
  }
  if (spec.name == "control_slot_engine") {
    return {
        {0, "issue_selected_control_slot", "Present the selected control graph slot.",
         "cycle_phase_o, control_valid_o, layer_o", "DPI records issue."},
        {1, "read_selected_control_metadata", "Read selected control-kind metadata.",
         "cycle_phase_o, control_kind_o", "DPI records metadata phase."},
        {2, "execute_selected_control_slot", "Execute the selected CPU/control operation.",
         "cycle_phase_o, control_ready_i", "DPI records execute phase."},
        {3, "commit_selected_control_slot", "Commit the selected control slot.",
         "cycle_phase_o, control_commit_o, issued_control_ops_o", "DPI checks committed count."},
    };
  }
  if (spec.name == "full_checkpoint_top") {
    return {
        {0, "present_top_graph_slot", "Present the next graph slot at the top boundary.",
         "graph_cycle_phase_o, active_layer_o, active_slot_o", "DPI records top slot issue."},
        {1, "start_selected_slot_engine", "Pulse exactly one selected slot engine.",
         "graph_cycle_phase_o, launch_linear_o, launch_control_o", "DPI counts launch pulses."},
        {2, "run_selected_slot_engine", "Run either the control slot or linear slot engine.",
         "graph_cycle_phase_o, linear_cycle_phase_o, control_cycle_phase_o",
         "DPI records selected engine progress."},
        {3, "commit_top_graph_slot", "Return slot done to the graph sequencer.",
         "graph_cycle_phase_o, issued_graph_slots_o", "DPI checks top committed slots."},
    };
  }
  throw std::runtime_error("no cycle steps for " + spec.name);
}

void validate_cycle_contract(const ModuleSpec& spec) {
  const std::vector<CycleStep> steps = cycle_steps(spec);
  const std::vector<std::string> phase_signals = cycle_phase_signals(spec);
  if (steps.empty()) {
    throw std::runtime_error(spec.name + " has no generated cycle contract");
  }
  if (phase_signals.empty()) {
    throw std::runtime_error(spec.name + " has no documented cycle phase signal");
  }
  for (std::size_t i = 0; i < steps.size(); ++i) {
    if (steps[i].cycle != static_cast<int>(i)) {
      throw std::runtime_error(spec.name + " cycle contract is not contiguous");
    }
    if (steps[i].phase.empty() || steps[i].responsibility.empty() ||
        steps[i].observed_signals.empty() || steps[i].dpi_check.empty()) {
      throw std::runtime_error(spec.name + " has an incomplete cycle contract row");
    }
  }
  const std::string expected_dpi = "e1_h1_full_dpi_cycle(\"" + spec.name + "\"";
  if (spec.probe_sv.find(expected_dpi) == std::string::npos) {
    throw std::runtime_error(spec.name + " probe does not report DPI cycles");
  }
}

void write_cycle_steps_json(std::ostringstream& out,
                            const std::vector<CycleStep>& steps,
                            const std::string& indent) {
  out << indent << "\"cycles\": [\n";
  for (std::size_t i = 0; i < steps.size(); ++i) {
    const CycleStep& step = steps[i];
    out << indent << "  {\"cycle\": " << step.cycle << ", \"phase\": \"" << step.phase
        << "\", \"responsibility\": \"" << step.responsibility
        << "\", \"observed_signals\": \"" << step.observed_signals
        << "\", \"dpi_check\": \"" << step.dpi_check << "\"}"
        << (i + 1 == steps.size() ? "\n" : ",\n");
  }
  out << indent << "]";
}

void write_cycle_contract_object_json(std::ostringstream& out,
                                      const ModuleSpec& spec,
                                      const std::string& indent) {
  const std::vector<CycleStep> steps = cycle_steps(spec);
  out << indent << "\"cycle_contract\": {\n";
  out << indent << "  \"template\": \"" << cycle_template_name(spec) << "\",\n";
  out << indent << "  \"cycle_period\": " << steps.size() << ",\n";
  write_string_array_json(out, "phase_signals", cycle_phase_signals(spec), indent + "  ");
  out << ",\n";
  write_cycle_steps_json(out, steps, indent + "  ");
  out << "\n" << indent << "}";
}

std::string module_interfaces_markdown(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "# Generated Full-Checkpoint RTL Module Interfaces\n\n";
  out << "Generated by `e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp`.\n";
  out << "Each section is the review contract for a generated RTL module and its "
         "module-only DPI probe.\n\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "## " << spec.name << "\n\n";
    out << "- Top module: `" << spec.top_module << "`\n";
    out << "- DPI probe: `" << spec.probe_module << "`\n\n";
    out << "### Input Signals\n\n";
    out << "| Signal | Width | Description |\n";
    out << "| --- | ---: | --- |\n";
    for (const SignalSpec& signal : spec.input_signals) {
      out << "| `" << signal.name << "` | " << signal.width << " | " << signal.description << " |\n";
    }
    out << "\n### Output Signals\n\n";
    out << "| Signal | Width | Description |\n";
    out << "| --- | ---: | --- |\n";
    for (const SignalSpec& signal : spec.output_signals) {
      out << "| `" << signal.name << "` | " << signal.width << " | " << signal.description << " |\n";
    }
    out << "\n### Cycle Notes\n\n";
    for (const std::string& note : spec.cycle_notes) {
      out << "- " << note << "\n";
    }
    out << "\n### Cycle Contract\n\n";
    out << "- Template: `" << cycle_template_name(spec) << "`\n";
    out << "- Period: " << cycle_steps(spec).size() << " cycles\n";
    out << "- Phase signal(s): ";
    const std::vector<std::string> phase_signals = cycle_phase_signals(spec);
    for (std::size_t j = 0; j < phase_signals.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "`" << phase_signals[j] << "`";
    }
    out << "\n\n";
    out << "| Cycle | Phase | Responsibility | Observed Signals | DPI Check |\n";
    out << "| ---: | --- | --- | --- | --- |\n";
    for (const CycleStep& step : cycle_steps(spec)) {
      out << "| " << step.cycle << " | `" << step.phase << "` | "
          << step.responsibility << " | " << step.observed_signals << " | "
          << step.dpi_check << " |\n";
    }
    if (i + 1 != specs.size()) {
      out << "\n";
    }
  }
  return out.str();
}

std::string manifest_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-full-checkpoint-generated-module-dpi-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp\",\n";
  out << "  \"scoreboard\": \"e1/e1-h1/generated/full_checkpoint_dpi/e1_h1_full_checkpoint_module_dpi_scoreboard.cpp\",\n";
  out << "  \"module_interfaces_doc\": \"e1/e1-h1/generated/full_checkpoint_dpi/module_interfaces.md\",\n";
  out << "  \"module_isolation_proof\": \"e1/e1-h1/generated/full_checkpoint_dpi/module_isolation.json\",\n";
  out << "  \"cycle_contract\": \"e1/e1-h1/generated/full_checkpoint_dpi/cycle_contract.json\",\n";
  out << "  \"module_test_plan\": \"e1/e1-h1/generated/full_checkpoint_dpi/module_test_plan.json\",\n";
  out << "  \"construction_rule\": \"one_generated_probe_per_full_checkpoint_rtl_module_with_cpp_dpi_driven_neighbors\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"top_module\": \"" << spec.top_module << "\",\n";
    out << "      \"probe_module\": \"" << spec.probe_module << "\",\n";
    out << "      \"scope\": \"generated_full_checkpoint_module_only\",\n";
    out << "      \"neighbors\": \"cpp_dpi_environment_or_declared_flist_dependencies\",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/full_checkpoint_dpi/" << spec.probe_module << ".sv\",\n";
    out << "      \"main\": \"e1/e1-h1/generated/full_checkpoint_dpi/" << spec.probe_module << "_main.cpp\",\n";
    out << "      \"flist\": \"e1/e1-h1/generated/full_checkpoint_dpi/flists/" << spec.name << ".f\",\n";
    out << "      \"module_test_plan\": \"e1/e1-h1/generated/full_checkpoint_dpi/module_test_plan.json\",\n";
    out << "      \"rtl\": [";
    for (std::size_t j = 0; j < spec.rtl.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "\"" << spec.rtl[j] << "\"";
    }
    out << "],\n";
    out << "      \"cycle_notes\": [";
    for (std::size_t j = 0; j < spec.cycle_notes.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "\"" << spec.cycle_notes[j] << "\"";
    }
    out << "],\n";
    write_signal_array_json(out, "input_signals", spec.input_signals, "      ");
    out << ",\n";
    write_signal_array_json(out, "output_signals", spec.output_signals, "      ");
    out << ",\n";
    write_cycle_contract_object_json(out, spec, "      ");
    out << "\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string module_isolation_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-full-checkpoint-module-isolation-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp\",\n";
  out << "  \"construction_rule\": \"one_probe_per_generated_module_with_only_declared_rtl_children\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"dut_module\": \"" << spec.top_module << "\",\n";
    out << "      \"dut_rtl\": \"" << spec.rtl.back() << "\",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/full_checkpoint_dpi/" << spec.probe_module << ".sv\",\n";
    out << "      \"flist\": \"e1/e1-h1/generated/full_checkpoint_dpi/flists/" << spec.name << ".f\",\n";
    out << "      \"boundary\": \"cpp_dpi_drives_every_neighbor_not_listed_as_allowed_child_module\",\n";
    write_string_array_json(out, "rtl_files", spec.rtl, "      ");
    out << ",\n";
    write_string_array_json(out, "allowed_child_modules", allowed_child_modules(spec), "      ");
    out << ",\n";
    write_string_array_json(out, "forbidden_child_modules", forbidden_child_modules(spec), "      ");
    out << ",\n";
    out << "      \"checks\": [\n";
    out << "        {\"name\": \"dut_rtl_defines_top_module\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"allowed_child_modules_present\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"forbidden_child_modules_absent\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"flist_contains_declared_rtl_plus_probe\", \"status\": \"pass\"}\n";
    out << "      ]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string cycle_contract_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-full-checkpoint-cycle-contract-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp\",\n";
  out << "  \"readme_diagram\": \"e1/e1-h1/docs/modules/README.md#cycle-diagram\",\n";
  out << "  \"construction_rule\": \"every_generated_module_has_contiguous_named_cycle_phases_and_dpi_cycle_reporting\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    const std::vector<CycleStep> steps = cycle_steps(spec);
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"top_module\": \"" << spec.top_module << "\",\n";
    out << "      \"probe_module\": \"" << spec.probe_module << "\",\n";
    out << "      \"readme_diagram\": \"e1/e1-h1/docs/modules/README.md#cycle-diagram\",\n";
    out << "      \"template\": \"" << cycle_template_name(spec) << "\",\n";
    out << "      \"cycle_period\": " << steps.size() << ",\n";
    write_string_array_json(out, "phase_signals", cycle_phase_signals(spec), "      ");
    out << ",\n";
    write_cycle_steps_json(out, steps, "      ");
    out << ",\n";
    out << "      \"checks\": [\n";
    out << "        {\"name\": \"cycle_indices_contiguous\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"cycle_phase_signals_documented\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"dpi_probe_reports_cycles\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"readme_cycle_diagram_declared\", \"status\": \"pass\"}\n";
    out << "      ]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::vector<std::string> verilator_fixed_args() {
  return {
      "--cc",
      "--exe",
      "--build",
      "--sv",
      "-Wall",
      "-Wno-DECLFILENAME",
      "-Wno-UNUSEDSIGNAL",
      "-Wno-UNUSEDPARAM",
      "-Wno-WIDTHEXPAND",
      "--timing",
  };
}

std::vector<std::string> expected_stdout_markers(const ModuleSpec& spec) {
  return {
      "module=" + spec.name,
      "E1_H1_FULL_MODULE_DPI_CYCLE",
  };
}

void write_verilator_object_json(std::ostringstream& out,
                                 const ModuleSpec& spec,
                                 const std::string& indent) {
  const std::string flist = "e1/e1-h1/generated/full_checkpoint_dpi/flists/" + spec.name + ".f";
  const std::string main = "e1/e1-h1/generated/full_checkpoint_dpi/" + spec.probe_module + "_main.cpp";
  const std::string scoreboard =
      "e1/e1-h1/generated/full_checkpoint_dpi/e1_h1_full_checkpoint_module_dpi_scoreboard.cpp";
  out << indent << "\"verilator\": {\n";
  out << indent << "  \"top_module\": \"" << spec.probe_module << "\",\n";
  out << indent << "  \"dut_module\": \"" << spec.top_module << "\",\n";
  out << indent << "  \"flist\": \"" << flist << "\",\n";
  out << indent << "  \"scoreboard\": \"" << scoreboard << "\",\n";
  out << indent << "  \"main\": \"" << main << "\",\n";
  out << indent << "  \"obj_dir_placeholder\": \"<obj_dir>\",\n";
  out << indent << "  \"run_executable\": \"V" << spec.probe_module << "\",\n";
  write_string_array_json(out, "fixed_args", verilator_fixed_args(), indent + "  ");
  out << ",\n";
  write_string_array_json(out, "expected_stdout_markers", expected_stdout_markers(spec), indent + "  ");
  out << "\n" << indent << "}";
}

std::string module_test_plan_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-full-checkpoint-module-dpi-test-plan-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp\",\n";
  out << "  \"runner\": \"verilator\",\n";
  out << "  \"construction_rule\": \"each_generated_full_checkpoint_module_has_a_generated_module_only_verilator_invocation\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"scope\": \"generated_full_checkpoint_module_only\",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/full_checkpoint_dpi/" << spec.probe_module << ".sv\",\n";
    write_verilator_object_json(out, spec, "      ");
    out << ",\n";
    out << "      \"checks\": [\n";
    out << "        {\"name\": \"probe_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"flist_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"scoreboard_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"main_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"verilator_top_is_probe_module\", \"status\": \"pass\"}\n";
    out << "      ]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string probe_header(const std::string& module_name) {
  std::ostringstream out;
  out << "`default_nettype none\n\n";
  out << "module e1_h1_full_checkpoint_module_dpi_" << module_name << ";\n";
  out << "  import \"DPI-C\" function void e1_h1_full_dpi_begin(input string module_name, input string vip_case);\n";
  out << "  import \"DPI-C\" function void e1_h1_full_dpi_cycle(input string module_name, input int cycle, input string phase);\n";
  out << "  import \"DPI-C\" function int e1_h1_full_dpi_expect_u32(\n";
  out << "    input string module_name,\n";
  out << "    input string signal_name,\n";
  out << "    input int cycle,\n";
  out << "    input int expected,\n";
  out << "    input int actual\n";
  out << "  );\n\n";
  out << "  task automatic tick;\n";
  out << "    clk_i = 1'b0; #1;\n";
  out << "    clk_i = 1'b1; #1;\n";
  out << "  endtask\n\n";
  out << "  task automatic expect_u32(input string signal_name, input int cycle, input int expected, input logic [31:0] actual);\n";
  out << "    if (e1_h1_full_dpi_expect_u32(\"" << module_name << "\", signal_name, cycle, expected, int'(actual)) == 0) begin\n";
  out << "      $fatal(1, \"" << module_name << " mismatch %s\", signal_name);\n";
  out << "    end\n";
  out << "  endtask\n\n";
  return out.str();
}

std::string probe_footer() {
  return "endmodule\n\n`default_nettype wire\n";
}

std::string sv_graph_sequencer() {
  std::ostringstream out;
  out << probe_header("graph_sequencer");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic busy_o;
  logic done_o;
  logic slot_valid_o;
  logic slot_ready_i;
  logic launch_control_o;
  logic launch_linear_o;
  logic op_done_i;
  logic [31:0] layer_o;
  logic [3:0] layer_slot_o;
  logic [2:0] linear_op_index_o;
  logic [2:0] control_op_index_o;
  logic [3:0] control_kind_o;
  logic [31:0] linear_tile_count_o;
  logic [31:0] issued_graph_slots_o;
  logic [1:0] cycle_phase_o;

  e1_h1_tinyllama_graph_sequencer u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .slot_valid_o(slot_valid_o),
    .slot_ready_i(slot_ready_i),
    .launch_control_o(launch_control_o),
    .launch_linear_o(launch_linear_o),
    .op_done_i(op_done_i),
    .layer_o(layer_o),
    .layer_slot_o(layer_slot_o),
    .linear_op_index_o(linear_op_index_o),
    .control_op_index_o(control_op_index_o),
    .control_kind_o(control_kind_o),
    .linear_tile_count_o(linear_tile_count_o),
    .issued_graph_slots_o(issued_graph_slots_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    int linear_launches;
    int control_launches;
    e1_h1_full_dpi_begin("graph_sequencer", "ordered_308_slot_graph");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    slot_ready_i = 1'b1;
    op_done_i = 1'b0;
    linear_launches = 0;
    control_launches = 0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 1600 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("graph_sequencer", cycle, "drive_ready_and_engine_done");
      op_done_i = (cycle_phase_o == 2'd2);
      if (launch_linear_o) linear_launches++;
      if (launch_control_o) control_launches++;
      tick();
    end
    expect_u32("issued_graph_slots_o", 0, 308, issued_graph_slots_o);
    expect_u32("linear_launches", 0, 154, linear_launches[31:0]);
    expect_u32("control_launches", 0, 154, control_launches[31:0]);
    if (!done_o) $fatal(1, "graph sequencer did not finish");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_control_slot_engine() {
  std::ostringstream out;
  out << probe_header("control_slot_engine");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic [31:0] layer_i;
  logic [2:0] control_op_index_i;
  logic [3:0] control_kind_i;
  logic busy_o;
  logic done_o;
  logic control_valid_o;
  logic control_ready_i;
  logic control_commit_o;
  logic [31:0] layer_o;
  logic [2:0] control_op_index_o;
  logic [3:0] control_kind_o;
  logic [31:0] issued_control_ops_o;
  logic [1:0] cycle_phase_o;

  e1_h1_tinyllama_control_slot_engine u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .layer_i(layer_i),
    .control_op_index_i(control_op_index_i),
    .control_kind_i(control_kind_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .control_valid_o(control_valid_o),
    .control_ready_i(control_ready_i),
    .control_commit_o(control_commit_o),
    .layer_o(layer_o),
    .control_op_index_o(control_op_index_o),
    .control_kind_o(control_kind_o),
    .issued_control_ops_o(issued_control_ops_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    e1_h1_full_dpi_begin("control_slot_engine", "single_control_slot");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    layer_i = 32'd3;
    control_op_index_i = 3'd2;
    control_kind_i = 4'd3;
    control_ready_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 16 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("control_slot_engine", cycle, "single_slot_cpu_control");
      control_ready_i = (cycle >= 1);
      tick();
    end
    expect_u32("issued_control_ops_o", 0, 1, issued_control_ops_o);
    expect_u32("layer_o", 0, 3, layer_o);
    expect_u32("control_op_index_o", 0, 2, {29'd0, control_op_index_o});
    expect_u32("control_kind_o", 0, 3, {28'd0, control_kind_o});
    if (!done_o) $fatal(1, "control slot engine did not finish");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_control_scheduler() {
  std::ostringstream out;
  out << probe_header("control_scheduler");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic busy_o;
  logic done_o;
  logic control_valid_o;
  logic control_ready_i;
  logic control_commit_o;
  logic [31:0] layer_o;
  logic [2:0] control_op_index_o;
  logic [3:0] layer_op_slot_o;
  logic [3:0] control_kind_o;
  logic [31:0] issued_control_ops_o;
  logic [1:0] cycle_phase_o;

  e1_h1_tinyllama_control_scheduler u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .control_valid_o(control_valid_o),
    .control_ready_i(control_ready_i),
    .control_commit_o(control_commit_o),
    .layer_o(layer_o),
    .control_op_index_o(control_op_index_o),
    .layer_op_slot_o(layer_op_slot_o),
    .control_kind_o(control_kind_o),
    .issued_control_ops_o(issued_control_ops_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    e1_h1_full_dpi_begin("control_scheduler", "all_154_control_ops");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    control_ready_i = 1'b1;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 900 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("control_scheduler", cycle, "issue_execute_commit_control");
      tick();
    end
    expect_u32("issued_control_ops_o", 0, 154, issued_control_ops_o);
    if (!done_o) $fatal(1, "control scheduler did not finish");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_linear_scheduler() {
  std::ostringstream out;
  out << probe_header("linear_scheduler");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic cmd_valid_o;
  logic cmd_ready_i;
  logic [31:0] cmd_input_addr_o;
  logic [31:0] cmd_weight_addr_o;
  logic [31:0] cmd_output_addr_o;
  logic [15:0] cmd_rows_o;
  logic [15:0] cmd_cols_o;
  logic [15:0] cmd_depth_o;
  logic array_done_i;
  logic array_error_i;
  logic [31:0] layer_o;
  logic [2:0] op_index_o;
  logic [8:0] input_tile_o;
  logic [8:0] output_tile_o;
  logic [31:0] issued_commands_o;
  logic [2:0] cycle_phase_o;

  e1_h1_tinyllama_linear_scheduler u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .cmd_valid_o(cmd_valid_o),
    .cmd_ready_i(cmd_ready_i),
    .cmd_input_addr_o(cmd_input_addr_o),
    .cmd_weight_addr_o(cmd_weight_addr_o),
    .cmd_output_addr_o(cmd_output_addr_o),
    .cmd_rows_o(cmd_rows_o),
    .cmd_cols_o(cmd_cols_o),
    .cmd_depth_o(cmd_depth_o),
    .array_done_i(array_done_i),
    .array_error_i(array_error_i),
    .layer_o(layer_o),
    .op_index_o(op_index_o),
    .input_tile_o(input_tile_o),
    .output_tile_o(output_tile_o),
    .issued_commands_o(issued_commands_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    e1_h1_full_dpi_begin("linear_scheduler", "first_four_tile_commands");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    cmd_ready_i = 1'b1;
    array_done_i = 1'b0;
    array_error_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 128 && issued_commands_o < 32'd4; cycle++) begin
      e1_h1_full_dpi_cycle("linear_scheduler", cycle, "cpu_tile_command_template");
      array_done_i = (cycle_phase_o == 3'd6);
      tick();
      array_done_i = 1'b0;
    end
    expect_u32("issued_commands_o", 0, 4, issued_commands_o);
    expect_u32("cmd_rows_o", 0, 16, {16'd0, cmd_rows_o});
    expect_u32("cmd_cols_o", 0, 16, {16'd0, cmd_cols_o});
    expect_u32("cmd_depth_o", 0, 16, {16'd0, cmd_depth_o});
    if (error_o) $fatal(1, "linear scheduler reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_linear_tile_engine() {
  std::ostringstream out;
  out << probe_header("linear_tile_engine");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic stream_valid_i;
  logic stream_ready_o;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic [31:0] issued_commands_o;
  logic [2:0] cycle_phase_o;
  logic [31:0] layer_o;
  logic [2:0] op_index_o;
  logic [8:0] input_tile_o;
  logic [8:0] output_tile_o;
  logic scheduler_cmd_valid_o;
  logic array_cmd_valid_o;
  logic array_cmd_ready_o;
  logic [31:0] cmd_input_addr_o;
  logic [31:0] cmd_weight_addr_o;
  logic [31:0] cmd_output_addr_o;
  logic [15:0] cmd_rows_o;
  logic [15:0] cmd_cols_o;
  logic [15:0] cmd_depth_o;
  logic buffer_array_valid_o;
  logic buffer_array_ready_o;
  logic [63:0] buffer_array_data_o;
  logic array_done_o;
  logic array_debug_busy_o;

  e1_h1_tinyllama_linear_tile_engine u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_o),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .issued_commands_o(issued_commands_o),
    .cycle_phase_o(cycle_phase_o),
    .layer_o(layer_o),
    .op_index_o(op_index_o),
    .input_tile_o(input_tile_o),
    .output_tile_o(output_tile_o),
    .scheduler_cmd_valid_o(scheduler_cmd_valid_o),
    .array_cmd_valid_o(array_cmd_valid_o),
    .array_cmd_ready_o(array_cmd_ready_o),
    .cmd_input_addr_o(cmd_input_addr_o),
    .cmd_weight_addr_o(cmd_weight_addr_o),
    .cmd_output_addr_o(cmd_output_addr_o),
    .cmd_rows_o(cmd_rows_o),
    .cmd_cols_o(cmd_cols_o),
    .cmd_depth_o(cmd_depth_o),
    .buffer_array_valid_o(buffer_array_valid_o),
    .buffer_array_ready_o(buffer_array_ready_o),
    .buffer_array_data_o(buffer_array_data_o),
    .array_done_o(array_done_o),
    .array_debug_busy_o(array_debug_busy_o)
  );

  initial begin
    e1_h1_full_dpi_begin("linear_tile_engine", "first_four_composed_tile_commands");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    for (int cycle = 0; cycle < 256 && issued_commands_o < 32'd4; cycle++) begin
      e1_h1_full_dpi_cycle("linear_tile_engine", cycle, "scheduler_latch_array_composition");
      stream_valid_i = 1'b1;
      stream_data_i = 64'h3000 + cycle[15:0];
      tick();
      start_i = 1'b0;
    end
    expect_u32("issued_commands_o", 0, 4, issued_commands_o);
    if (error_o) $fatal(1, "linear tile engine reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_linear_slot_engine() {
  std::ostringstream out;
  out << probe_header("linear_slot_engine");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic [31:0] layer_i;
  logic [2:0] op_index_i;
  logic stream_valid_i;
  logic stream_ready_o;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic [31:0] issued_commands_o;
  logic [31:0] expected_commands_o;
  logic [2:0] cycle_phase_o;
  logic [31:0] layer_o;
  logic [2:0] op_index_o;
  logic [8:0] input_tile_o;
  logic [8:0] output_tile_o;
  logic scheduler_cmd_valid_o;
  logic array_cmd_valid_o;
  logic array_cmd_ready_o;
  logic [31:0] cmd_input_addr_o;
  logic [31:0] cmd_weight_addr_o;
  logic [31:0] cmd_output_addr_o;
  logic [15:0] cmd_rows_o;
  logic [15:0] cmd_cols_o;
  logic [15:0] cmd_depth_o;
  logic buffer_array_valid_o;
  logic buffer_array_ready_o;
  logic [63:0] buffer_array_data_o;
  logic array_done_o;
  logic array_debug_busy_o;

  e1_h1_tinyllama_linear_slot_engine #(
    .SmokeMaxTilesPerLinearSlot(2)
  ) u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .layer_i(layer_i),
    .op_index_i(op_index_i),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_o),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .issued_commands_o(issued_commands_o),
    .expected_commands_o(expected_commands_o),
    .cycle_phase_o(cycle_phase_o),
    .layer_o(layer_o),
    .op_index_o(op_index_o),
    .input_tile_o(input_tile_o),
    .output_tile_o(output_tile_o),
    .scheduler_cmd_valid_o(scheduler_cmd_valid_o),
    .array_cmd_valid_o(array_cmd_valid_o),
    .array_cmd_ready_o(array_cmd_ready_o),
    .cmd_input_addr_o(cmd_input_addr_o),
    .cmd_weight_addr_o(cmd_weight_addr_o),
    .cmd_output_addr_o(cmd_output_addr_o),
    .cmd_rows_o(cmd_rows_o),
    .cmd_cols_o(cmd_cols_o),
    .cmd_depth_o(cmd_depth_o),
    .buffer_array_valid_o(buffer_array_valid_o),
    .buffer_array_ready_o(buffer_array_ready_o),
    .buffer_array_data_o(buffer_array_data_o),
    .array_done_o(array_done_o),
    .array_debug_busy_o(array_debug_busy_o)
  );

  initial begin
    e1_h1_full_dpi_begin("linear_slot_engine", "bounded_two_tile_linear_slot");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    layer_i = 32'd0;
    op_index_i = 3'd0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    for (int cycle = 0; cycle < 128 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("linear_slot_engine", cycle, "slot_local_scheduler_latch_array");
      stream_valid_i = 1'b1;
      stream_data_i = 64'h4000 + cycle[15:0];
      tick();
      start_i = 1'b0;
    end
    expect_u32("issued_commands_o", 0, 2, issued_commands_o);
    expect_u32("expected_commands_o", 0, 2, expected_commands_o);
    if (!done_o) $fatal(1, "linear slot engine did not finish");
    if (error_o) $fatal(1, "linear slot engine reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_full_top() {
  std::ostringstream out;
  out << probe_header("full_checkpoint_top");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic stream_valid_i;
  logic stream_ready_o;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic [31:0] issued_graph_slots_o;
  logic [31:0] issued_linear_commands_o;
  logic [31:0] issued_control_ops_o;
  logic [31:0] active_layer_o;
  logic [3:0] active_slot_o;
  logic [1:0] graph_cycle_phase_o;
  logic [2:0] linear_cycle_phase_o;
  logic [1:0] control_cycle_phase_o;
  logic launch_linear_o;
  logic launch_control_o;
  logic linear_busy_o;
  logic control_busy_o;
  logic buffer_array_valid_o;
  logic buffer_array_ready_o;
  logic array_done_o;
  logic array_debug_busy_o;
  logic debug_scheduler_cmd_valid_o;
  logic debug_array_cmd_valid_o;
  logic debug_array_cmd_ready_o;
  logic [31:0] debug_cmd_input_addr_o;
  logic [31:0] debug_cmd_weight_addr_o;
  logic [31:0] debug_cmd_output_addr_o;
  logic [15:0] debug_cmd_rows_o;
  logic [15:0] debug_cmd_cols_o;
  logic [15:0] debug_cmd_depth_o;
  logic [31:0] debug_linear_layer_o;
  logic [2:0] debug_linear_op_index_o;
  logic [8:0] debug_linear_input_tile_o;
  logic [8:0] debug_linear_output_tile_o;

  e1_h1_tinyllama_full_checkpoint_top #(
    .SmokeMaxTilesPerLinearSlot(1)
  ) u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_o),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .issued_graph_slots_o(issued_graph_slots_o),
    .issued_linear_commands_o(issued_linear_commands_o),
    .issued_control_ops_o(issued_control_ops_o),
    .active_layer_o(active_layer_o),
    .active_slot_o(active_slot_o),
    .graph_cycle_phase_o(graph_cycle_phase_o),
    .linear_cycle_phase_o(linear_cycle_phase_o),
    .control_cycle_phase_o(control_cycle_phase_o),
    .launch_linear_o(launch_linear_o),
    .launch_control_o(launch_control_o),
    .linear_busy_o(linear_busy_o),
    .control_busy_o(control_busy_o),
    .buffer_array_valid_o(buffer_array_valid_o),
    .buffer_array_ready_o(buffer_array_ready_o),
    .array_done_o(array_done_o),
    .array_debug_busy_o(array_debug_busy_o),
    .debug_scheduler_cmd_valid_o(debug_scheduler_cmd_valid_o),
    .debug_array_cmd_valid_o(debug_array_cmd_valid_o),
    .debug_array_cmd_ready_o(debug_array_cmd_ready_o),
    .debug_cmd_input_addr_o(debug_cmd_input_addr_o),
    .debug_cmd_weight_addr_o(debug_cmd_weight_addr_o),
    .debug_cmd_output_addr_o(debug_cmd_output_addr_o),
    .debug_cmd_rows_o(debug_cmd_rows_o),
    .debug_cmd_cols_o(debug_cmd_cols_o),
    .debug_cmd_depth_o(debug_cmd_depth_o),
    .debug_linear_layer_o(debug_linear_layer_o),
    .debug_linear_op_index_o(debug_linear_op_index_o),
    .debug_linear_input_tile_o(debug_linear_input_tile_o),
    .debug_linear_output_tile_o(debug_linear_output_tile_o)
  );

  initial begin
    int linear_launches;
    int control_launches;
    e1_h1_full_dpi_begin("full_checkpoint_top", "bounded_all_308_graph_slots");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    linear_launches = 0;
    control_launches = 0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    for (int cycle = 0; cycle < 10000 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("full_checkpoint_top", cycle, "graph_dispatch_to_slot_engines");
      stream_valid_i = 1'b1;
      stream_data_i = 64'h5000 + cycle[15:0];
      if (launch_linear_o) linear_launches++;
      if (launch_control_o) control_launches++;
      tick();
      start_i = 1'b0;
    end
    expect_u32("issued_graph_slots_o", 0, 308, issued_graph_slots_o);
    expect_u32("issued_linear_commands_o", 0, 154, issued_linear_commands_o);
    expect_u32("issued_control_ops_o", 0, 154, issued_control_ops_o);
    expect_u32("linear_launches", 0, 154, linear_launches[31:0]);
    expect_u32("control_launches", 0, 154, control_launches[31:0]);
    if (!done_o) $fatal(1, "full checkpoint top did not finish");
    if (error_o) $fatal(1, "full checkpoint top reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::vector<ModuleSpec> module_specs() {
  const std::string gen = "e1/e1-h1/generated/full_checkpoint/";
  const std::string stream = "e1/e1-h1/rtl/imp2/e1_h1_stream_sram.sv";
  const std::string array = "e1/e1-h1/rtl/imp2/e1_h1_systolic_array.sv";
  return {
      {
          "linear_scheduler",
          "e1_h1_tinyllama_linear_scheduler",
          "e1_h1_full_checkpoint_module_dpi_linear_scheduler",
          {gen + "e1_h1_tinyllama_linear_scheduler.sv"},
          {"cycle 0 setup", "cycle 2 command handshake", "cycle 6 array done"},
          {
              {"clk_i", "1", "Scheduler clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts full linear tile-command enumeration."},
              {"cmd_ready_i", "1", "Array-side command ready handshake."},
              {"array_done_i", "1", "Array completion for the issued tile command."},
              {"array_error_i", "1", "Array error for the issued tile command."},
          },
          {
              {"busy_o", "1", "Scheduler is running."},
              {"done_o", "1", "All full-checkpoint tile commands have been issued."},
              {"error_o", "1", "Scheduler observed array error."},
              {"cmd_valid_o", "1", "Tile command is valid."},
              {"cmd_input_addr_o", "32", "Input tile base address."},
              {"cmd_weight_addr_o", "32", "Weight tile base address."},
              {"cmd_output_addr_o", "32", "Output tile base address."},
              {"cmd_rows_o", "16", "Tile row count."},
              {"cmd_cols_o", "16", "Tile column count."},
              {"cmd_depth_o", "16", "Tile reduction depth."},
              {"layer_o", "32", "Current TinyLlama layer."},
              {"op_index_o", "3", "Current linear op index within the layer."},
              {"input_tile_o", "9", "Current input tile index."},
              {"output_tile_o", "9", "Current output tile index."},
              {"issued_commands_o", "32", "Number of accepted tile commands."},
              {"cycle_phase_o", "3", "Current 8-cycle tile-template phase."},
          },
          sv_linear_scheduler(),
      },
      {
          "linear_tile_engine",
          "e1_h1_tinyllama_linear_tile_engine",
          "e1_h1_full_checkpoint_module_dpi_linear_tile_engine",
          {gen + "e1_h1_tinyllama_linear_scheduler.sv", stream, array, gen + "e1_h1_tinyllama_linear_tile_engine.sv"},
          {"cycle 1 scheduler valid", "cycle 2 gated array command", "cycles 3-6 latch/array transfer"},
          {
              {"clk_i", "1", "Tile engine clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts the linear tile engine."},
              {"stream_valid_i", "1", "External input stream valid into the latch buffer."},
              {"stream_data_i", "64", "External input stream data into the latch buffer."},
              {"stream_last_i", "1", "External input stream packet-last marker."},
              {"stream_error_i", "1", "External input stream error marker."},
          },
          {
              {"stream_ready_o", "1", "Latch buffer can accept stream data."},
              {"busy_o", "1", "Scheduler is running."},
              {"done_o", "1", "Scheduler completed all tile commands."},
              {"error_o", "1", "Scheduler or array reported error."},
              {"issued_commands_o", "32", "Number of accepted tile commands."},
              {"cycle_phase_o", "3", "Current 8-cycle tile-template phase."},
              {"layer_o", "32", "Current TinyLlama layer."},
              {"op_index_o", "3", "Current linear op index."},
              {"input_tile_o", "9", "Current input tile index."},
              {"output_tile_o", "9", "Current output tile index."},
              {"scheduler_cmd_valid_o", "1", "Ungated scheduler command-valid signal."},
              {"array_cmd_valid_o", "1", "Gated command-valid signal sent to the array."},
              {"array_cmd_ready_o", "1", "Array command-ready signal."},
              {"cmd_input_addr_o", "32", "Input tile base address."},
              {"cmd_weight_addr_o", "32", "Weight tile base address."},
              {"cmd_output_addr_o", "32", "Output tile base address."},
              {"cmd_rows_o", "16", "Tile row count."},
              {"cmd_cols_o", "16", "Tile column count."},
              {"cmd_depth_o", "16", "Tile reduction depth."},
              {"buffer_array_valid_o", "1", "Latch-buffer output valid toward the array."},
              {"buffer_array_ready_o", "1", "Array input-ready signal toward the latch buffer."},
              {"buffer_array_data_o", "64", "Latched stream data toward the array."},
              {"array_done_o", "1", "Array completion pulse."},
              {"array_debug_busy_o", "1", "Array debug busy signal."},
          },
          sv_linear_tile_engine(),
      },
      {
          "control_scheduler",
          "e1_h1_tinyllama_control_scheduler",
          "e1_h1_full_checkpoint_module_dpi_control_scheduler",
          {gen + "e1_h1_tinyllama_control_scheduler.sv"},
          {"cycle 0 control issue", "cycle 2 execute", "cycle 3 commit"},
          {
              {"clk_i", "1", "Control scheduler clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts all-layer control-op scheduling."},
              {"control_ready_i", "1", "CPU/control side accepts the current control op."},
          },
          {
              {"busy_o", "1", "Control scheduler is running."},
              {"done_o", "1", "All control ops have been issued."},
              {"control_valid_o", "1", "Current control op is valid."},
              {"control_commit_o", "1", "Current control op commits this cycle."},
              {"layer_o", "32", "Current TinyLlama layer."},
              {"control_op_index_o", "3", "Control op index within the layer."},
              {"layer_op_slot_o", "4", "Original ordered graph slot for the control op."},
              {"control_kind_o", "4", "Encoded control operation kind."},
              {"issued_control_ops_o", "32", "Number of committed control ops."},
              {"cycle_phase_o", "2", "Current 4-cycle control template phase."},
          },
          sv_control_scheduler(),
      },
      {
          "graph_sequencer",
          "e1_h1_tinyllama_graph_sequencer",
          "e1_h1_full_checkpoint_module_dpi_graph_sequencer",
          {gen + "e1_h1_tinyllama_graph_sequencer.sv"},
          {"cycle 0 present graph slot", "cycle 1 launch selected engine", "cycle 2 wait done", "cycle 3 commit"},
          {
              {"clk_i", "1", "Graph sequencer clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts ordered TinyLlama graph-slot sequencing."},
              {"slot_ready_i", "1", "Downstream accepts the presented graph slot."},
              {"op_done_i", "1", "Selected slot engine has completed."},
          },
          {
              {"busy_o", "1", "Graph sequencer is running."},
              {"done_o", "1", "All graph slots have been issued."},
              {"slot_valid_o", "1", "Current ordered graph slot is valid."},
              {"launch_control_o", "1", "Launch pulse for the control slot engine."},
              {"launch_linear_o", "1", "Launch pulse for the linear slot engine."},
              {"layer_o", "32", "Current TinyLlama layer."},
              {"layer_slot_o", "4", "Ordered graph slot within the current layer."},
              {"linear_op_index_o", "3", "Linear op index for linear slots."},
              {"control_op_index_o", "3", "Control op index for control slots."},
              {"control_kind_o", "4", "Encoded control operation kind."},
              {"linear_tile_count_o", "32", "Planned tile count for linear slots."},
              {"issued_graph_slots_o", "32", "Number of committed graph slots."},
              {"cycle_phase_o", "2", "Current 4-cycle graph template phase."},
          },
          sv_graph_sequencer(),
      },
      {
          "linear_slot_engine",
          "e1_h1_tinyllama_linear_slot_engine",
          "e1_h1_full_checkpoint_module_dpi_linear_slot_engine",
          {stream, array, gen + "e1_h1_tinyllama_linear_slot_engine.sv"},
          {"cycle 1 slot command valid", "cycle 2 array command", "cycles 3-6 separated latch/array"},
          {
              {"clk_i", "1", "Linear slot engine clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts one selected linear graph slot."},
              {"layer_i", "32", "Layer selected by the graph sequencer."},
              {"op_index_i", "3", "Linear op index selected by the graph sequencer."},
              {"stream_valid_i", "1", "External input stream valid into the latch buffer."},
              {"stream_data_i", "64", "External input stream data into the latch buffer."},
              {"stream_last_i", "1", "External input stream packet-last marker."},
              {"stream_error_i", "1", "External input stream error marker."},
          },
          {
              {"stream_ready_o", "1", "Latch buffer can accept stream data."},
              {"busy_o", "1", "Linear slot engine is running."},
              {"done_o", "1", "Selected linear slot is complete."},
              {"error_o", "1", "Array reported error for the selected slot."},
              {"issued_commands_o", "32", "Number of accepted tile commands for this slot."},
              {"expected_commands_o", "32", "Bounded or natural tile count for this slot."},
              {"cycle_phase_o", "3", "Current 8-cycle tile-template phase."},
              {"layer_o", "32", "Latched layer for this slot."},
              {"op_index_o", "3", "Latched linear op index for this slot."},
              {"input_tile_o", "9", "Current input tile index."},
              {"output_tile_o", "9", "Current output tile index."},
              {"scheduler_cmd_valid_o", "1", "Ungated slot command-valid signal."},
              {"array_cmd_valid_o", "1", "Gated command-valid signal sent to the array."},
              {"array_cmd_ready_o", "1", "Array command-ready signal."},
              {"cmd_input_addr_o", "32", "Input tile base address."},
              {"cmd_weight_addr_o", "32", "Weight tile base address."},
              {"cmd_output_addr_o", "32", "Output tile base address."},
              {"cmd_rows_o", "16", "Tile row count."},
              {"cmd_cols_o", "16", "Tile column count."},
              {"cmd_depth_o", "16", "Tile reduction depth."},
              {"buffer_array_valid_o", "1", "Latch-buffer output valid toward the array."},
              {"buffer_array_ready_o", "1", "Array input-ready signal toward the latch buffer."},
              {"buffer_array_data_o", "64", "Latched stream data toward the array."},
              {"array_done_o", "1", "Array completion pulse."},
              {"array_debug_busy_o", "1", "Array debug busy signal."},
          },
          sv_linear_slot_engine(),
      },
      {
          "control_slot_engine",
          "e1_h1_tinyllama_control_slot_engine",
          "e1_h1_full_checkpoint_module_dpi_control_slot_engine",
          {gen + "e1_h1_tinyllama_control_slot_engine.sv"},
          {"cycle 0 control valid", "cycle 2 execute", "cycle 3 commit"},
          {
              {"clk_i", "1", "Control slot engine clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts one selected control graph slot."},
              {"layer_i", "32", "Layer selected by the graph sequencer."},
              {"control_op_index_i", "3", "Control op index selected by the graph sequencer."},
              {"control_kind_i", "4", "Encoded control operation kind."},
              {"control_ready_i", "1", "CPU/control side accepts the selected control slot."},
          },
          {
              {"busy_o", "1", "Control slot engine is running."},
              {"done_o", "1", "Selected control slot is complete."},
              {"control_valid_o", "1", "Selected control slot is valid."},
              {"control_commit_o", "1", "Selected control slot commits this cycle."},
              {"layer_o", "32", "Latched layer for this slot."},
              {"control_op_index_o", "3", "Latched control op index for this slot."},
              {"control_kind_o", "4", "Latched control operation kind."},
              {"issued_control_ops_o", "32", "Number of committed control ops for this slot."},
              {"cycle_phase_o", "2", "Current 4-cycle control template phase."},
          },
          sv_control_slot_engine(),
      },
      {
          "full_checkpoint_top",
          "e1_h1_tinyllama_full_checkpoint_top",
          "e1_h1_full_checkpoint_module_dpi_full_checkpoint_top",
          {
              gen + "e1_h1_tinyllama_graph_sequencer.sv",
              stream,
              array,
              gen + "e1_h1_tinyllama_linear_slot_engine.sv",
              gen + "e1_h1_tinyllama_control_slot_engine.sv",
              gen + "e1_h1_tinyllama_full_checkpoint_top.sv",
          },
          {"cycle 0 graph slot", "cycle 1 slot start", "cycle 2 selected engine runs", "cycle 3 graph commit"},
          {
              {"clk_i", "1", "Full-checkpoint top clock."},
              {"rst_ni", "1", "Active-low reset."},
              {"start_i", "1", "Starts ordered full-checkpoint graph-slot execution."},
              {"stream_valid_i", "1", "External input stream valid into linear slots."},
              {"stream_data_i", "64", "External input stream data into linear slots."},
              {"stream_last_i", "1", "External input stream packet-last marker."},
              {"stream_error_i", "1", "External input stream error marker."},
          },
          {
              {"stream_ready_o", "1", "Selected linear slot can accept stream data."},
              {"busy_o", "1", "Full-checkpoint top is running."},
              {"done_o", "1", "All graph slots have completed."},
              {"error_o", "1", "Selected linear slot reported error."},
              {"issued_graph_slots_o", "32", "Number of committed graph slots."},
              {"issued_linear_commands_o", "32", "Number of accepted bounded linear tile commands."},
              {"issued_control_ops_o", "32", "Number of committed control slots."},
              {"active_layer_o", "32", "Current TinyLlama layer."},
              {"active_slot_o", "4", "Current ordered graph slot within the layer."},
              {"graph_cycle_phase_o", "2", "Current 4-cycle graph template phase."},
              {"linear_cycle_phase_o", "3", "Current linear slot tile-template phase."},
              {"control_cycle_phase_o", "2", "Current control slot template phase."},
              {"launch_linear_o", "1", "Launch pulse for the linear slot engine."},
              {"launch_control_o", "1", "Launch pulse for the control slot engine."},
              {"linear_busy_o", "1", "Linear slot engine is running."},
              {"control_busy_o", "1", "Control slot engine is running."},
              {"buffer_array_valid_o", "1", "Latch-buffer output valid toward the array."},
              {"buffer_array_ready_o", "1", "Array input-ready signal toward the latch buffer."},
              {"array_done_o", "1", "Array completion pulse."},
              {"array_debug_busy_o", "1", "Array debug busy signal."},
              {"debug_scheduler_cmd_valid_o", "1", "Observed scheduler command-valid at the full top boundary."},
              {"debug_array_cmd_valid_o", "1", "Observed array command-valid at the full top boundary."},
              {"debug_array_cmd_ready_o", "1", "Observed array command-ready at the full top boundary."},
              {"debug_cmd_input_addr_o", "32", "Observed input tile base address for payload schedule checks."},
              {"debug_cmd_weight_addr_o", "32", "Observed weight tile base address for payload schedule checks."},
              {"debug_cmd_output_addr_o", "32", "Observed output tile base address for payload schedule checks."},
              {"debug_cmd_rows_o", "16", "Observed tile row count for payload schedule checks."},
              {"debug_cmd_cols_o", "16", "Observed tile column count for payload schedule checks."},
              {"debug_cmd_depth_o", "16", "Observed tile reduction depth for payload schedule checks."},
              {"debug_linear_layer_o", "32", "Observed linear slot layer for payload schedule checks."},
              {"debug_linear_op_index_o", "3", "Observed linear op index for payload schedule checks."},
              {"debug_linear_input_tile_o", "9", "Observed input tile index for payload schedule checks."},
              {"debug_linear_output_tile_o", "9", "Observed output tile index for payload schedule checks."},
          },
          sv_full_top(),
      },
  };
}

fs::path parse_path_arg(int argc, char** argv, const std::string& flag, const fs::path& default_value) {
  for (int i = 1; i + 1 < argc; ++i) {
    if (argv[i] == flag) {
      return fs::path(argv[i + 1]);
    }
  }
  return default_value;
}

}  // namespace

int main(int argc, char** argv) {
  try {
    const fs::path repo_root = parse_path_arg(argc, argv, "--repo-root", fs::current_path());
    const fs::path output_dir = parse_path_arg(
        argc,
        argv,
        "--output-dir",
        repo_root / "e1/e1-h1/generated/full_checkpoint_dpi");
    const fs::path rel_output_dir = fs::relative(output_dir, repo_root);
    const fs::path flist_dir = output_dir / "flists";
    const std::vector<ModuleSpec> specs = module_specs();

    for (const ModuleSpec& spec : specs) {
      validate_rtl_inputs(repo_root, spec);
      validate_isolation(repo_root, spec);
      validate_cycle_contract(spec);
    }

    write_text(output_dir / "e1_h1_full_checkpoint_module_dpi_scoreboard.cpp", scoreboard_cpp());
    for (const ModuleSpec& spec : specs) {
      const fs::path probe_path = rel_output_dir / (spec.probe_module + ".sv");
      write_text(output_dir / (spec.probe_module + ".sv"), spec.probe_sv);
      write_text(output_dir / (spec.probe_module + "_main.cpp"), main_cpp(spec));
      write_text(flist_dir / (spec.name + ".f"), flist_text(probe_path, spec));
    }
    write_text(output_dir / "manifest.json", manifest_json(specs));
    write_text(output_dir / "module_interfaces.md", module_interfaces_markdown(specs));
    write_text(output_dir / "module_isolation.json", module_isolation_json(specs));
    write_text(output_dir / "cycle_contract.json", cycle_contract_json(specs));
    write_text(output_dir / "module_test_plan.json", module_test_plan_json(specs));

    std::cout << "PASS e1_h1_generate_full_checkpoint_module_dpi " << specs.size()
              << " modules -> " << output_dir.generic_string() << "\n";
    return 0;
  } catch (const std::exception& ex) {
    std::cerr << "FAIL e1_h1_generate_full_checkpoint_module_dpi " << ex.what() << "\n";
    return 1;
  }
}
