// SPDX-License-Identifier: Apache-2.0
// Generate per-module DPI equivalence probes for the E1-H1 imp1/imp2 scheme.

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

struct CycleStep {
  int cycle;
  std::string phase;
  std::string responsibility;
  std::string observed_signals;
  std::string dpi_check;
};

struct ModuleSpec {
  std::string name;
  std::string concern;
  std::string top_module;
  std::string probe_module;
  std::string imp2_rtl;
  std::vector<std::string> vip_cases;
  std::vector<std::string> cycle_notes;
  bool latch_buffer;
  std::string probe_sv;
};

std::string read_text(const fs::path& path) {
  std::ifstream input(path);
  if (!input) {
    throw std::runtime_error("cannot read " + path.string());
  }
  std::ostringstream buffer;
  buffer << input.rdbuf();
  return buffer.str();
}

void write_text(const fs::path& path, const std::string& text) {
  fs::create_directories(path.parent_path());
  std::ofstream output(path);
  if (!output) {
    throw std::runtime_error("cannot write " + path.string());
  }
  output << text;
}

bool contains(const std::string& text, const std::string& needle) {
  return text.find(needle) != std::string::npos;
}

void require_contains(const std::string& text, const std::string& needle, const fs::path& path) {
  if (!contains(text, needle)) {
    throw std::runtime_error(path.string() + " is missing required text: " + needle);
  }
}

void validate_manifest_inputs(const fs::path& repo_root, const ModuleSpec& spec) {
  const fs::path ip_path = repo_root / "e1/e1-h1/ip" / (spec.name + ".json");
  const fs::path vip_path = repo_root / "e1/e1-h1/vip" / (spec.name + ".json");
  const std::string ip = read_text(ip_path);
  const std::string vip = read_text(vip_path);

  require_contains(ip, "\"schema\": \"e1-h1-ip-v0\"", ip_path);
  require_contains(ip, "\"name\": \"" + spec.name + "\"", ip_path);
  require_contains(ip, "\"module\": \"" + spec.top_module + "\"", ip_path);
  require_contains(ip, "\"rtl\": \"" + spec.imp2_rtl + "\"", ip_path);
  require_contains(ip, "\"active\": \"imp2\"", ip_path);
  require_contains(ip, "\"reference\": \"imp1\"", ip_path);
  require_contains(ip, "\"acceptance\": \"verilator_dpi_vip_equivalent_to_imp1\"", ip_path);

  require_contains(vip, "\"schema\": \"e1-h1-module-vip-v0\"", vip_path);
  require_contains(vip, "\"name\": \"" + spec.name + "\"", vip_path);
  require_contains(vip, "\"top_module\": \"" + spec.top_module + "\"", vip_path);
  require_contains(vip, "\"rtl\": \"" + spec.imp2_rtl + "\"", vip_path);
  require_contains(vip, "\"kind\": \"module_only\"", vip_path);
  require_contains(vip, "\"allowed_systemverilog_modules\"", vip_path);
  require_contains(vip, "\"" + spec.top_module + "\"", vip_path);
  require_contains(vip, "\"neighbors\": \"cpp_environment\"", vip_path);
  for (const std::string& vip_case : spec.vip_cases) {
    require_contains(vip, "\"" + vip_case + "\"", vip_path);
  }
}

std::string scoreboard_cpp() {
  return R"cpp(// SPDX-License-Identifier: Apache-2.0
// Generated by e1/e1-h1/tools/generate_module_dpi.cpp.

#include <cstdio>

namespace {

const char* g_module = "";
const char* g_case = "";

}  // namespace

extern "C" void e1_h1_module_dpi_begin(const char* module_name, const char* vip_case) {
  g_module = module_name;
  g_case = vip_case;
  std::printf("E1_H1_MODULE_DPI_BEGIN module=%s case=%s\n", g_module, g_case);
}

extern "C" void e1_h1_module_dpi_cycle(const char* module_name, int cycle, const char* phase) {
  std::printf("E1_H1_MODULE_DPI_CYCLE module=%s cycle=%d phase=%s\n", module_name, cycle, phase);
}

extern "C" int e1_h1_module_dpi_compare_u32(
    const char* signal_name,
    int cycle,
    int imp1_value,
    int imp2_value) {
  if (imp1_value != imp2_value) {
    std::fprintf(
        stderr,
        "E1_H1_MODULE_DPI_MISMATCH module=%s case=%s signal=%s cycle=%d imp1=0x%x imp2=0x%x\n",
        g_module,
        g_case,
        signal_name,
        cycle,
        static_cast<unsigned>(imp1_value),
        static_cast<unsigned>(imp2_value));
    return 0;
  }
  return 1;
}
)cpp";
}

std::string main_cpp(const ModuleSpec& spec) {
  std::ostringstream out;
  out << "// SPDX-License-Identifier: Apache-2.0\n";
  out << "// Generated by e1/e1-h1/tools/generate_module_dpi.cpp.\n\n";
  out << "#include \"V" << spec.probe_module << ".h\"\n";
  out << "#include \"verilated.h\"\n\n";
  out << "int main(int argc, char** argv) {\n";
  out << "  VerilatedContext context;\n";
  out << "  context.commandArgs(argc, argv);\n";
  out << "  V" << spec.probe_module << " top{&context};\n";
  out << "  while (!context.gotFinish() && context.time() < 1000) {\n";
  out << "    top.eval();\n";
  out << "    context.timeInc(1);\n";
  out << "  }\n";
  out << "  return context.gotFinish() ? 0 : 1;\n";
  out << "}\n";
  return out.str();
}

std::string flist_text(const fs::path& probe, const ModuleSpec& spec) {
  std::ostringstream out;
  out << "e1/e1-h1/dpi/e1_h1_imp1_reference.sv\n";
  out << spec.imp2_rtl << "\n";
  out << probe.generic_string() << "\n";
  return out.str();
}

const std::vector<std::string>& known_design_modules() {
  static const std::vector<std::string> modules = {
      "e1_h1_control_cpu",
      "e1_h1_rgmii_ethernet_ingress",
      "e1_h1_stream_sram",
      "e1_h1_config_sram",
      "e1_h1_systolic_array",
  };
  return modules;
}

std::string reference_module(const ModuleSpec& spec) {
  if (spec.name == "control_cpu") {
    return "e1_h1_imp1_control_cpu_ref";
  }
  if (spec.name == "rgmii_ethernet_ingress") {
    return "e1_h1_imp1_rgmii_ethernet_ingress_ref";
  }
  if (spec.name == "ingress_sram") {
    return "e1_h1_imp1_stream_sram_ref";
  }
  if (spec.name == "activation_sram" || spec.name == "accumulator_sram") {
    return "e1_h1_imp1_config_sram_ref";
  }
  if (spec.name == "systolic_array") {
    return "e1_h1_imp1_systolic_array_ref";
  }
  throw std::runtime_error("no reference module for " + spec.name);
}

std::vector<std::string> allowed_verification_modules(const ModuleSpec& spec) {
  return {reference_module(spec), spec.top_module};
}

std::vector<std::string> forbidden_design_neighbors(const ModuleSpec& spec) {
  std::vector<std::string> forbidden;
  for (const std::string& module : known_design_modules()) {
    if (module != spec.top_module) {
      forbidden.push_back(module);
    }
  }
  return forbidden;
}

void write_string_array_json(std::ostringstream& out,
                             const std::string& key,
                             const std::vector<std::string>& values,
                             const std::string& indent) {
  out << indent << "\"" << key << "\": [";
  for (std::size_t i = 0; i < values.size(); ++i) {
    out << (i == 0 ? "" : ", ") << "\"" << values[i] << "\"";
  }
  out << "]";
}

std::string cycle_template_name(const ModuleSpec& spec) {
  if (spec.name == "control_cpu") {
    return "cpu_command_8_cycle_template";
  }
  if (spec.name == "rgmii_ethernet_ingress") {
    return "digital_rgmii_ingress_10_cycle_template";
  }
  if (spec.name == "ingress_sram") {
    return "latch_buffer_6_cycle_template";
  }
  if (spec.name == "activation_sram" || spec.name == "accumulator_sram") {
    return "config_sram_3_cycle_template";
  }
  if (spec.name == "systolic_array") {
    return "systolic_array_8_cycle_template";
  }
  throw std::runtime_error("no cycle template for " + spec.name);
}

std::vector<CycleStep> cycle_steps(const ModuleSpec& spec) {
  if (spec.name == "control_cpu") {
    return {
        {0, "reset_release", "Release reset and present the first command payload.",
         "cmd_valid_o, debug_halted_o", "DPI compares imp1 and imp2 CPU outputs."},
        {1, "command_backpressure", "Hold cmd_valid_o while command ready is asserted late.",
         "cmd_valid_o, cmd_ready_i", "DPI compares the held command payload."},
        {2, "command_handshake", "Accept the CPU command at the array boundary.",
         "cmd_valid_o, cmd_ready_i, cmd_*_o", "DPI compares command fields."},
        {3, "wait_for_array", "Wait for array completion without instantiating array RTL.",
         "array_done_i, debug_halted_o", "DPI drives array_done_i from C++/probe stimulus."},
        {4, "wait_for_array_stable", "Keep waiting with no new command issue.",
         "cmd_valid_o, array_done_i", "DPI compares no-spurious-command behavior."},
        {5, "array_completion", "Observe array_done_i and move toward halt.",
         "array_done_i, debug_halted_o", "DPI compares completion behavior."},
        {6, "halt_transition", "Enter the debug halted state.",
         "debug_halted_o", "DPI compares halt transition."},
        {7, "halted_idle", "Remain halted with no extra command.",
         "cmd_valid_o, debug_halted_o", "DPI compares final idle state."},
    };
  }
  if (spec.name == "rgmii_ethernet_ingress") {
    return {
        {0, "idle_after_reset", "Hold digital RGMII input idle after reset.",
         "rgmii_rx_ctl_i, stream_valid_o", "DPI compares idle stream outputs."},
        {1, "frame_nibble_0", "Start a minimum digital RGMII frame.",
         "rgmii_rx_ctl_i, rgmii_rxd_i", "DPI compares stream assembly."},
        {2, "frame_nibble_1", "Shift the second RGMII nibble.",
         "rgmii_rxd_i", "DPI compares stream assembly."},
        {3, "frame_nibble_2", "Shift the third RGMII nibble.",
         "rgmii_rxd_i", "DPI compares stream assembly."},
        {4, "frame_nibble_3", "Shift the fourth RGMII nibble.",
         "rgmii_rxd_i", "DPI compares stream assembly."},
        {5, "frame_nibble_4", "Shift the final active RGMII nibble.",
         "rgmii_rxd_i, rgmii_rx_ctl_i", "DPI compares stream assembly."},
        {6, "frame_gap", "Drop receive control before downstream accepts.",
         "rgmii_rx_ctl_i, stream_ready_i", "DPI compares backpressure behavior."},
        {7, "downstream_accept", "Allow the stream output to drain.",
         "stream_ready_i, stream_valid_o", "DPI compares output handshake."},
        {8, "drain_stream", "Drain any remaining stream output.",
         "stream_ready_i, stream_data_o", "DPI compares final stream word."},
        {9, "return_idle", "Return the digital ingress path to idle.",
         "stream_valid_o, stream_last_o, stream_error_o", "DPI compares idle return."},
    };
  }
  if (spec.name == "ingress_sram") {
    return {
        {0, "latch_first_word", "Latch the first stream word while the array is not ready.",
         "stream_valid_i, array_ready_i, array_valid_o", "DPI compares latched valid/data."},
        {1, "hold_latched_word", "Hold the latched word under array backpressure.",
         "array_ready_i, array_valid_o, array_data_o", "DPI compares held data."},
        {2, "release_latched_word", "Release the latched word when array_ready_i rises.",
         "array_ready_i, array_valid_o, array_data_o", "DPI compares release behavior."},
        {3, "latch_next_clean_word", "Latch a later clean stream word.",
         "stream_valid_i, stream_error_i", "DPI compares accept behavior."},
        {4, "reject_error_word", "Reject an error-marked stream word.",
         "stream_error_i, stream_last_i", "DPI compares error filtering."},
        {5, "empty_or_ready", "Return to empty or ready state.",
         "stream_ready_o, array_valid_o", "DPI compares final latch state."},
    };
  }
  if (spec.name == "activation_sram" || spec.name == "accumulator_sram") {
    return {
        {0, "initialization_latch", "Latch initialized_q after reset release.",
         "initialized_q", "DPI compares parameterized imp1 and imp2 initialized state."},
        {1, "initialized_hold_0", "Hold initialized_q in the configured SRAM shell.",
         "initialized_q", "DPI compares hold behavior."},
        {2, "initialized_hold_1", "Continue holding initialized_q.",
         "initialized_q", "DPI compares final hold behavior."},
    };
  }
  if (spec.name == "systolic_array") {
    return {
        {0, "array_idle", "Keep the array idle and command-ready after reset.",
         "cmd_ready_o, debug_busy_o", "DPI compares idle readiness."},
        {1, "accept_array_command", "Accept the command from probe/C++ stimulus.",
         "cmd_valid_i, cmd_ready_o, cmd_*_i", "DPI compares command acceptance."},
        {2, "enter_busy", "Enter busy state before input beats arrive.",
         "debug_busy_o, input_ready_o", "DPI compares busy transition."},
        {3, "consume_input_beat_0", "Consume the first input beat.",
         "input_valid_i, input_ready_o, input_data_i", "DPI compares input readiness."},
        {4, "consume_input_beat_1", "Consume the second input beat.",
         "input_valid_i, input_ready_o, input_data_i", "DPI compares input readiness."},
        {5, "consume_input_beat_2", "Consume the third input beat.",
         "input_valid_i, input_ready_o, input_data_i", "DPI compares input readiness."},
        {6, "completion_pulse", "Consume the final beat and pulse done_o.",
         "input_valid_i, done_o, debug_busy_o", "DPI compares completion."},
        {7, "return_ready", "Return to ready/idle state for the next command.",
         "cmd_ready_o, done_o, debug_busy_o", "DPI compares return-to-ready."},
    };
  }
  throw std::runtime_error("no cycle steps for " + spec.name);
}

void validate_cycle_contract(const ModuleSpec& spec) {
  const std::vector<CycleStep> steps = cycle_steps(spec);
  if (steps.empty()) {
    throw std::runtime_error(spec.name + " has no generated cycle contract");
  }
  for (std::size_t i = 0; i < steps.size(); ++i) {
    if (steps[i].cycle != static_cast<int>(i)) {
      throw std::runtime_error(spec.name + " cycle contract is not contiguous");
    }
    if (steps[i].phase.empty() || steps[i].responsibility.empty() ||
        steps[i].observed_signals.empty() || steps[i].dpi_check.empty()) {
      throw std::runtime_error(spec.name + " has incomplete cycle contract row");
    }
  }
  const std::string expected_dpi = "e1_h1_module_dpi_cycle(\"" + spec.name + "\"";
  if (spec.probe_sv.find(expected_dpi) == std::string::npos) {
    throw std::runtime_error(spec.name + " probe does not report DPI cycles");
  }
}

void validate_isolation(const fs::path& repo_root, const ModuleSpec& spec) {
  const fs::path reference_path = repo_root / "e1/e1-h1/dpi/e1_h1_imp1_reference.sv";
  const std::string reference_text = read_text(reference_path);
  const std::string imp2_text = read_text(repo_root / spec.imp2_rtl);
  if (!contains(reference_text, "module " + reference_module(spec))) {
    throw std::runtime_error(spec.name + " reference module is missing");
  }
  if (!contains(imp2_text, "module " + spec.top_module)) {
    throw std::runtime_error(spec.name + " imp2 RTL does not define " + spec.top_module);
  }
  for (const std::string& module : allowed_verification_modules(spec)) {
    if (!contains(spec.probe_sv, module)) {
      throw std::runtime_error(spec.name + " probe is missing allowed module " + module);
    }
  }
  for (const std::string& module : forbidden_design_neighbors(spec)) {
    if (contains(spec.probe_sv, module)) {
      throw std::runtime_error(spec.name + " probe unexpectedly references " + module);
    }
  }
}

void write_cycle_steps_json(std::ostringstream& out,
                            const std::vector<CycleStep>& steps,
                            const std::string& indent) {
  out << indent << "\"cycles\": [\n";
  for (std::size_t i = 0; i < steps.size(); ++i) {
    const CycleStep& step = steps[i];
    out << indent << "  {\"cycle\": " << step.cycle << ", \"phase\": \"" << step.phase
        << "\", \"responsibility\": \"" << step.responsibility
        << "\", \"observed_signals\": \"" << step.observed_signals
        << "\", \"dpi_check\": \"" << step.dpi_check << "\"}"
        << (i + 1 == steps.size() ? "\n" : ",\n");
  }
  out << indent << "]";
}

void write_cycle_contract_object_json(std::ostringstream& out,
                                      const ModuleSpec& spec,
                                      const std::string& indent) {
  const std::vector<CycleStep> steps = cycle_steps(spec);
  out << indent << "\"cycle_contract\": {\n";
  out << indent << "  \"template\": \"" << cycle_template_name(spec) << "\",\n";
  out << indent << "  \"cycle_period\": " << steps.size() << ",\n";
  out << indent << "  \"phase_source\": \"e1_h1_module_dpi_cycle\",\n";
  write_cycle_steps_json(out, steps, indent + "  ");
  out << "\n" << indent << "}";
}

std::string module_isolation_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-module-dpi-isolation-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_module_dpi.cpp\",\n";
  out << "  \"construction_rule\": \"one_imp2_dut_per_probe_with_imp1_reference_and_cpp_dpi_neighbors_only\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"dut_module\": \"" << spec.top_module << "\",\n";
    out << "      \"reference_module\": \"" << reference_module(spec) << "\",\n";
    out << "      \"imp2_rtl\": \"" << spec.imp2_rtl << "\",\n";
    out << "      \"reference_rtl\": \"e1/e1-h1/dpi/e1_h1_imp1_reference.sv\",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/module_dpi/" << spec.probe_module << ".sv\",\n";
    out << "      \"flist\": \"e1/e1-h1/generated/module_dpi/flists/" << spec.name << ".f\",\n";
    out << "      \"boundary\": \"cpp_dpi_drives_all_neighbors_other_than_the_imp1_reference_oracle\",\n";
    write_string_array_json(out, "allowed_verification_modules", allowed_verification_modules(spec), "      ");
    out << ",\n";
    write_string_array_json(out, "forbidden_design_neighbors", forbidden_design_neighbors(spec), "      ");
    out << ",\n";
    out << "      \"checks\": [\n";
    out << "        {\"name\": \"imp2_rtl_defines_dut_module\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"reference_module_defined\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"probe_instantiates_only_dut_and_reference\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"forbidden_design_neighbors_absent\", \"status\": \"pass\"}\n";
    out << "      ]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string cycle_contract_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-module-dpi-cycle-contract-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_module_dpi.cpp\",\n";
  out << "  \"readme_diagram\": \"e1/e1-h1/docs/modules/README.md#cycle-diagram\",\n";
  out << "  \"construction_rule\": \"each_base_ip_probe_reports_contiguous_named_cycles_through_dpi\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    const std::vector<CycleStep> steps = cycle_steps(spec);
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"top_module\": \"" << spec.top_module << "\",\n";
    out << "      \"probe_module\": \"" << spec.probe_module << "\",\n";
    out << "      \"readme_diagram\": \"e1/e1-h1/docs/modules/README.md#cycle-diagram\",\n";
    out << "      \"template\": \"" << cycle_template_name(spec) << "\",\n";
    out << "      \"cycle_period\": " << steps.size() << ",\n";
    out << "      \"phase_source\": \"e1_h1_module_dpi_cycle\",\n";
    write_cycle_steps_json(out, steps, "      ");
    out << ",\n";
    out << "      \"checks\": [\n";
    out << "        {\"name\": \"cycle_indices_contiguous\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"dpi_probe_reports_cycles\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"readme_cycle_diagram_declared\", \"status\": \"pass\"}\n";
    out << "      ]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::vector<std::string> verilator_fixed_args() {
  return {
      "--cc",
      "--exe",
      "--build",
      "--sv",
      "-Wall",
      "-Wno-DECLFILENAME",
      "-Wno-UNUSEDSIGNAL",
      "-Wno-UNUSEDPARAM",
      "-Wno-WIDTHEXPAND",
      "--timing",
  };
}

std::vector<std::string> expected_stdout_markers(const ModuleSpec& spec) {
  return {
      "module=" + spec.name,
      "E1_H1_MODULE_DPI_CYCLE",
  };
}

void write_verilator_object_json(std::ostringstream& out,
                                 const ModuleSpec& spec,
                                 const std::string& indent) {
  const std::string flist = "e1/e1-h1/generated/module_dpi/flists/" + spec.name + ".f";
  const std::string main = "e1/e1-h1/generated/module_dpi/" + spec.probe_module + "_main.cpp";
  const std::string scoreboard = "e1/e1-h1/generated/module_dpi/e1_h1_module_dpi_scoreboard.cpp";
  out << indent << "\"verilator\": {\n";
  out << indent << "  \"top_module\": \"" << spec.probe_module << "\",\n";
  out << indent << "  \"dut_module\": \"" << spec.top_module << "\",\n";
  out << indent << "  \"flist\": \"" << flist << "\",\n";
  out << indent << "  \"scoreboard\": \"" << scoreboard << "\",\n";
  out << indent << "  \"main\": \"" << main << "\",\n";
  out << indent << "  \"obj_dir_placeholder\": \"<obj_dir>\",\n";
  out << indent << "  \"run_executable\": \"V" << spec.probe_module << "\",\n";
  write_string_array_json(out, "fixed_args", verilator_fixed_args(), indent + "  ");
  out << ",\n";
  write_string_array_json(out, "expected_stdout_markers", expected_stdout_markers(spec), indent + "  ");
  out << "\n" << indent << "}";
}

std::string module_test_plan_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-module-dpi-test-plan-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_module_dpi.cpp\",\n";
  out << "  \"runner\": \"verilator\",\n";
  out << "  \"construction_rule\": \"each_base_ip_has_a_generated_module_only_verilator_invocation\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"scope\": \"module_only\",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/module_dpi/" << spec.probe_module << ".sv\",\n";
    write_verilator_object_json(out, spec, "      ");
    out << ",\n";
    out << "      \"checks\": [\n";
    out << "        {\"name\": \"probe_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"flist_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"scoreboard_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"main_exists\", \"status\": \"pass\"},\n";
    out << "        {\"name\": \"verilator_top_is_probe_module\", \"status\": \"pass\"}\n";
    out << "      ]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string manifest_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-generated-module-dpi-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_module_dpi.cpp\",\n";
  out << "  \"scoreboard\": \"e1/e1-h1/generated/module_dpi/e1_h1_module_dpi_scoreboard.cpp\",\n";
  out << "  \"module_isolation_proof\": \"e1/e1-h1/generated/module_dpi/module_isolation.json\",\n";
  out << "  \"cycle_contract\": \"e1/e1-h1/generated/module_dpi/cycle_contract.json\",\n";
  out << "  \"module_test_plan\": \"e1/e1-h1/generated/module_dpi/module_test_plan.json\",\n";
  out << "  \"reference_implementation\": \"imp1\",\n";
  out << "  \"candidate_implementation\": \"imp2\",\n";
  out << "  \"construction_rule\": \"one_generated_probe_per_ip_with_only_that_systemverilog_dut_and_cpp_dpi_neighbors\",\n";
  out << "  \"separation_of_concerns\": {\n";
  out << "    \"control_cpu\": \"CPU command issue is tested without the systolic array RTL; completion and ready are C++/DPI-driven inputs.\",\n";
  out << "    \"systolic_array\": \"The array is tested without CPU RTL; command and input streams are C++/DPI-driven inputs.\",\n";
  out << "    \"ingress_sram\": \"The stream buffer is the explicit latched boundary between Ethernet ingress and the array input stream.\"\n";
  out << "  },\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"concern\": \"" << spec.concern << "\",\n";
    out << "      \"top_module\": \"" << spec.top_module << "\",\n";
    out << "      \"reference_module\": \"" << reference_module(spec) << "\",\n";
    out << "      \"probe_module\": \"" << spec.probe_module << "\",\n";
    out << "      \"scope\": \"module_only\",\n";
    out << "      \"neighbors\": \"cpp_dpi_environment\",\n";
    out << "      \"latch_buffer\": " << (spec.latch_buffer ? "true" : "false") << ",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/module_dpi/" << spec.probe_module << ".sv\",\n";
    out << "      \"main\": \"e1/e1-h1/generated/module_dpi/" << spec.probe_module << "_main.cpp\",\n";
    out << "      \"flist\": \"e1/e1-h1/generated/module_dpi/flists/" << spec.name << ".f\",\n";
    out << "      \"imp2_rtl\": \"" << spec.imp2_rtl << "\",\n";
    out << "      \"module_test_plan\": \"e1/e1-h1/generated/module_dpi/module_test_plan.json\",\n";
    out << "      \"vip_cases\": [";
    for (std::size_t j = 0; j < spec.vip_cases.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "\"" << spec.vip_cases[j] << "\"";
    }
    out << "],\n";
    out << "      \"cycle_notes\": [";
    for (std::size_t j = 0; j < spec.cycle_notes.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "\"" << spec.cycle_notes[j] << "\"";
    }
    out << "],\n";
    write_cycle_contract_object_json(out, spec, "      ");
    out << "\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string sv_control_cpu() {
  return R"sv(`default_nettype none

module e1_h1_module_dpi_control_cpu;
  import "DPI-C" function void e1_h1_module_dpi_begin(input string module_name, input string vip_case);
  import "DPI-C" function void e1_h1_module_dpi_cycle(input string module_name, input int cycle, input string phase);
  import "DPI-C" function int e1_h1_module_dpi_compare_u32(
    input string signal_name,
    input int cycle,
    input int imp1_value,
    input int imp2_value
  );

  logic clk_i;
  logic rst_ni;
  logic cmd_ready_i;
  logic array_done_i;
  logic array_error_i;
  logic cmd_valid_imp1, cmd_valid_imp2;
  logic [31:0] cmd_input_addr_imp1, cmd_input_addr_imp2;
  logic [31:0] cmd_weight_addr_imp1, cmd_weight_addr_imp2;
  logic [31:0] cmd_output_addr_imp1, cmd_output_addr_imp2;
  logic [15:0] cmd_rows_imp1, cmd_rows_imp2;
  logic [15:0] cmd_cols_imp1, cmd_cols_imp2;
  logic [15:0] cmd_depth_imp1, cmd_depth_imp2;
  logic debug_halted_imp1, debug_halted_imp2;

  e1_h1_imp1_control_cpu_ref u_imp1 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .cmd_valid_o(cmd_valid_imp1),
    .cmd_ready_i(cmd_ready_i),
    .cmd_input_addr_o(cmd_input_addr_imp1),
    .cmd_weight_addr_o(cmd_weight_addr_imp1),
    .cmd_output_addr_o(cmd_output_addr_imp1),
    .cmd_rows_o(cmd_rows_imp1),
    .cmd_cols_o(cmd_cols_imp1),
    .cmd_depth_o(cmd_depth_imp1),
    .array_done_i(array_done_i),
    .array_error_i(array_error_i),
    .debug_halted_o(debug_halted_imp1)
  );

  e1_h1_control_cpu u_imp2 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .cmd_valid_o(cmd_valid_imp2),
    .cmd_ready_i(cmd_ready_i),
    .cmd_input_addr_o(cmd_input_addr_imp2),
    .cmd_weight_addr_o(cmd_weight_addr_imp2),
    .cmd_output_addr_o(cmd_output_addr_imp2),
    .cmd_rows_o(cmd_rows_imp2),
    .cmd_cols_o(cmd_cols_imp2),
    .cmd_depth_o(cmd_depth_imp2),
    .array_done_i(array_done_i),
    .array_error_i(array_error_i),
    .debug_halted_o(debug_halted_imp2)
  );

  task automatic tick;
    clk_i = 1'b0; #1;
    clk_i = 1'b1; #1;
  endtask

  task automatic check32(input string name, input int cycle, input logic [31:0] imp1, input logic [31:0] imp2);
    if (e1_h1_module_dpi_compare_u32(name, cycle, int'(imp1), int'(imp2)) == 0) begin
      $fatal(1, "control_cpu mismatch %s cycle %0d", name, cycle);
    end
  endtask

  task automatic check_outputs(input int cycle);
    check32("cmd_valid_o", cycle, {31'd0, cmd_valid_imp1}, {31'd0, cmd_valid_imp2});
    check32("cmd_input_addr_o", cycle, cmd_input_addr_imp1, cmd_input_addr_imp2);
    check32("cmd_weight_addr_o", cycle, cmd_weight_addr_imp1, cmd_weight_addr_imp2);
    check32("cmd_output_addr_o", cycle, cmd_output_addr_imp1, cmd_output_addr_imp2);
    check32("cmd_rows_o", cycle, {16'd0, cmd_rows_imp1}, {16'd0, cmd_rows_imp2});
    check32("cmd_cols_o", cycle, {16'd0, cmd_cols_imp1}, {16'd0, cmd_cols_imp2});
    check32("cmd_depth_o", cycle, {16'd0, cmd_depth_imp1}, {16'd0, cmd_depth_imp2});
    check32("debug_halted_o", cycle, {31'd0, debug_halted_imp1}, {31'd0, debug_halted_imp2});
  endtask

  initial begin
    e1_h1_module_dpi_begin("control_cpu", "module_only_control_cpu");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    cmd_ready_i = 1'b0;
    array_done_i = 1'b0;
    array_error_i = 1'b0;
    tick();
    rst_ni = 1'b1;
    for (int cycle = 0; cycle < 8; cycle++) begin
      e1_h1_module_dpi_cycle("control_cpu", cycle, "drive");
      cmd_ready_i = (cycle >= 1 && cycle <= 2);
      array_done_i = (cycle == 5);
      array_error_i = 1'b0;
      tick();
      e1_h1_module_dpi_cycle("control_cpu", cycle, "sample");
      check_outputs(cycle);
    end
    $finish;
  end
endmodule

`default_nettype wire
)sv";
}

std::string sv_systolic_array() {
  return R"sv(`default_nettype none

module e1_h1_module_dpi_systolic_array;
  import "DPI-C" function void e1_h1_module_dpi_begin(input string module_name, input string vip_case);
  import "DPI-C" function void e1_h1_module_dpi_cycle(input string module_name, input int cycle, input string phase);
  import "DPI-C" function int e1_h1_module_dpi_compare_u32(
    input string signal_name,
    input int cycle,
    input int imp1_value,
    input int imp2_value
  );

  logic clk_i;
  logic rst_ni;
  logic cmd_valid_i;
  logic [31:0] cmd_input_addr_i;
  logic [31:0] cmd_weight_addr_i;
  logic [31:0] cmd_output_addr_i;
  logic [15:0] cmd_rows_i;
  logic [15:0] cmd_cols_i;
  logic [15:0] cmd_depth_i;
  logic input_valid_i;
  logic [63:0] input_data_i;
  logic cmd_ready_imp1, cmd_ready_imp2;
  logic input_ready_imp1, input_ready_imp2;
  logic done_imp1, done_imp2;
  logic error_imp1, error_imp2;
  logic debug_busy_imp1, debug_busy_imp2;

  e1_h1_imp1_systolic_array_ref u_imp1 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .cmd_valid_i(cmd_valid_i),
    .cmd_ready_o(cmd_ready_imp1),
    .cmd_input_addr_i(cmd_input_addr_i),
    .cmd_weight_addr_i(cmd_weight_addr_i),
    .cmd_output_addr_i(cmd_output_addr_i),
    .cmd_rows_i(cmd_rows_i),
    .cmd_cols_i(cmd_cols_i),
    .cmd_depth_i(cmd_depth_i),
    .input_valid_i(input_valid_i),
    .input_ready_o(input_ready_imp1),
    .input_data_i(input_data_i),
    .done_o(done_imp1),
    .error_o(error_imp1),
    .debug_busy_o(debug_busy_imp1)
  );

  e1_h1_systolic_array u_imp2 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .cmd_valid_i(cmd_valid_i),
    .cmd_ready_o(cmd_ready_imp2),
    .cmd_input_addr_i(cmd_input_addr_i),
    .cmd_weight_addr_i(cmd_weight_addr_i),
    .cmd_output_addr_i(cmd_output_addr_i),
    .cmd_rows_i(cmd_rows_i),
    .cmd_cols_i(cmd_cols_i),
    .cmd_depth_i(cmd_depth_i),
    .input_valid_i(input_valid_i),
    .input_ready_o(input_ready_imp2),
    .input_data_i(input_data_i),
    .done_o(done_imp2),
    .error_o(error_imp2),
    .debug_busy_o(debug_busy_imp2)
  );

  task automatic tick;
    clk_i = 1'b0; #1;
    clk_i = 1'b1; #1;
  endtask

  task automatic check1(input string name, input int cycle, input logic imp1, input logic imp2);
    if (e1_h1_module_dpi_compare_u32(name, cycle, int'({31'd0, imp1}), int'({31'd0, imp2})) == 0) begin
      $fatal(1, "systolic_array mismatch %s cycle %0d", name, cycle);
    end
  endtask

  task automatic check_outputs(input int cycle);
    check1("cmd_ready_o", cycle, cmd_ready_imp1, cmd_ready_imp2);
    check1("input_ready_o", cycle, input_ready_imp1, input_ready_imp2);
    check1("done_o", cycle, done_imp1, done_imp2);
    check1("error_o", cycle, error_imp1, error_imp2);
    check1("debug_busy_o", cycle, debug_busy_imp1, debug_busy_imp2);
  endtask

  initial begin
    e1_h1_module_dpi_begin("systolic_array", "module_only_systolic_array");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    cmd_valid_i = 1'b0;
    cmd_input_addr_i = 32'h0001_0000;
    cmd_weight_addr_i = 32'h0004_0000;
    cmd_output_addr_i = 32'h0008_0000;
    cmd_rows_i = 16'd16;
    cmd_cols_i = 16'd16;
    cmd_depth_i = 16'd16;
    input_valid_i = 1'b0;
    input_data_i = 64'd0;
    tick();
    rst_ni = 1'b1;
    for (int cycle = 0; cycle < 8; cycle++) begin
      e1_h1_module_dpi_cycle("systolic_array", cycle, "drive");
      cmd_valid_i = (cycle == 1);
      input_valid_i = (cycle >= 3 && cycle <= 6);
      input_data_i = 64'h1000 + cycle[7:0];
      tick();
      e1_h1_module_dpi_cycle("systolic_array", cycle, "sample");
      check_outputs(cycle);
    end
    $finish;
  end
endmodule

`default_nettype wire
)sv";
}

std::string sv_stream_sram() {
  return R"sv(`default_nettype none

module e1_h1_module_dpi_ingress_sram;
  import "DPI-C" function void e1_h1_module_dpi_begin(input string module_name, input string vip_case);
  import "DPI-C" function void e1_h1_module_dpi_cycle(input string module_name, input int cycle, input string phase);
  import "DPI-C" function int e1_h1_module_dpi_compare_u32(
    input string signal_name,
    input int cycle,
    input int imp1_value,
    input int imp2_value
  );

  logic clk_i;
  logic rst_ni;
  logic stream_valid_i;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic array_ready_i;
  logic stream_ready_imp1, stream_ready_imp2;
  logic array_valid_imp1, array_valid_imp2;
  logic [63:0] array_data_imp1, array_data_imp2;

  e1_h1_imp1_stream_sram_ref u_imp1 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_imp1),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .array_valid_o(array_valid_imp1),
    .array_ready_i(array_ready_i),
    .array_data_o(array_data_imp1)
  );

  e1_h1_stream_sram u_imp2 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_imp2),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .array_valid_o(array_valid_imp2),
    .array_ready_i(array_ready_i),
    .array_data_o(array_data_imp2)
  );

  task automatic tick;
    clk_i = 1'b0; #1;
    clk_i = 1'b1; #1;
  endtask

  task automatic check32(input string name, input int cycle, input logic [31:0] imp1, input logic [31:0] imp2);
    if (e1_h1_module_dpi_compare_u32(name, cycle, int'(imp1), int'(imp2)) == 0) begin
      $fatal(1, "ingress_sram mismatch %s cycle %0d", name, cycle);
    end
  endtask

  task automatic check_outputs(input int cycle);
    check32("stream_ready_o", cycle, {31'd0, stream_ready_imp1}, {31'd0, stream_ready_imp2});
    check32("array_valid_o", cycle, {31'd0, array_valid_imp1}, {31'd0, array_valid_imp2});
    check32("array_data_o.lo", cycle, array_data_imp1[31:0], array_data_imp2[31:0]);
    check32("array_data_o.hi", cycle, array_data_imp1[63:32], array_data_imp2[63:32]);
  endtask

  initial begin
    e1_h1_module_dpi_begin("ingress_sram", "module_only_latched_buffer");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    array_ready_i = 1'b0;
    tick();
    rst_ni = 1'b1;
    for (int cycle = 0; cycle < 6; cycle++) begin
      e1_h1_module_dpi_cycle("ingress_sram", cycle, "drive_latch_boundary");
      stream_valid_i = (cycle == 0 || cycle == 3 || cycle == 4);
      stream_data_i = 64'h2000 + cycle[7:0];
      stream_last_i = (cycle == 4);
      stream_error_i = (cycle == 4);
      array_ready_i = (cycle >= 2);
      tick();
      e1_h1_module_dpi_cycle("ingress_sram", cycle, "sample_latched_output");
      check_outputs(cycle);
    end
    $finish;
  end
endmodule

`default_nettype wire
)sv";
}

std::string sv_rgmii() {
  return R"sv(`default_nettype none

module e1_h1_module_dpi_rgmii_ethernet_ingress;
  import "DPI-C" function void e1_h1_module_dpi_begin(input string module_name, input string vip_case);
  import "DPI-C" function void e1_h1_module_dpi_cycle(input string module_name, input int cycle, input string phase);
  import "DPI-C" function int e1_h1_module_dpi_compare_u32(
    input string signal_name,
    input int cycle,
    input int imp1_value,
    input int imp2_value
  );

  logic clk_i;
  logic rst_ni;
  logic rgmii_rx_clk_i;
  logic [3:0] rgmii_rxd_i;
  logic rgmii_rx_ctl_i;
  logic stream_ready_i;
  logic stream_valid_imp1, stream_valid_imp2;
  logic [63:0] stream_data_imp1, stream_data_imp2;
  logic stream_last_imp1, stream_last_imp2;
  logic stream_error_imp1, stream_error_imp2;

  e1_h1_imp1_rgmii_ethernet_ingress_ref u_imp1 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .rgmii_rx_clk_i(rgmii_rx_clk_i),
    .rgmii_rxd_i(rgmii_rxd_i),
    .rgmii_rx_ctl_i(rgmii_rx_ctl_i),
    .stream_valid_o(stream_valid_imp1),
    .stream_ready_i(stream_ready_i),
    .stream_data_o(stream_data_imp1),
    .stream_last_o(stream_last_imp1),
    .stream_error_o(stream_error_imp1)
  );

  e1_h1_rgmii_ethernet_ingress u_imp2 (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .rgmii_rx_clk_i(rgmii_rx_clk_i),
    .rgmii_rxd_i(rgmii_rxd_i),
    .rgmii_rx_ctl_i(rgmii_rx_ctl_i),
    .stream_valid_o(stream_valid_imp2),
    .stream_ready_i(stream_ready_i),
    .stream_data_o(stream_data_imp2),
    .stream_last_o(stream_last_imp2),
    .stream_error_o(stream_error_imp2)
  );

  task automatic tick_core;
    clk_i = 1'b0; #1;
    clk_i = 1'b1; #1;
  endtask

  task automatic tick_rgmii;
    rgmii_rx_clk_i = 1'b0; #1;
    rgmii_rx_clk_i = 1'b1; #1;
  endtask

  task automatic check32(input string name, input int cycle, input logic [31:0] imp1, input logic [31:0] imp2);
    if (e1_h1_module_dpi_compare_u32(name, cycle, int'(imp1), int'(imp2)) == 0) begin
      $fatal(1, "rgmii_ethernet_ingress mismatch %s cycle %0d", name, cycle);
    end
  endtask

  task automatic check_outputs(input int cycle);
    check32("stream_valid_o", cycle, {31'd0, stream_valid_imp1}, {31'd0, stream_valid_imp2});
    check32("stream_data_o.lo", cycle, stream_data_imp1[31:0], stream_data_imp2[31:0]);
    check32("stream_data_o.hi", cycle, stream_data_imp1[63:32], stream_data_imp2[63:32]);
    check32("stream_last_o", cycle, {31'd0, stream_last_imp1}, {31'd0, stream_last_imp2});
    check32("stream_error_o", cycle, {31'd0, stream_error_imp1}, {31'd0, stream_error_imp2});
  endtask

  initial begin
    e1_h1_module_dpi_begin("rgmii_ethernet_ingress", "module_only_rgmii_ingress");
    clk_i = 1'b0;
    rgmii_rx_clk_i = 1'b0;
    rst_ni = 1'b0;
    rgmii_rxd_i = 4'd0;
    rgmii_rx_ctl_i = 1'b0;
    stream_ready_i = 1'b0;
    tick_core();
    tick_rgmii();
    rst_ni = 1'b1;
    for (int cycle = 0; cycle < 10; cycle++) begin
      e1_h1_module_dpi_cycle("rgmii_ethernet_ingress", cycle, "drive_rgmii");
      rgmii_rx_ctl_i = (cycle >= 1 && cycle <= 5);
      stream_ready_i = (cycle >= 7);
      rgmii_rxd_i = cycle[3:0];
      tick_rgmii();
      e1_h1_module_dpi_cycle("rgmii_ethernet_ingress", cycle, "sample_stream");
      check_outputs(cycle);
    end
    $finish;
  end
endmodule

`default_nettype wire
)sv";
}

std::string sv_config_sram(const std::string& probe_module,
                           const std::string& module_name,
                           int size_bytes,
                           int data_width,
                           int banks) {
  std::ostringstream out;
  out << "`default_nettype none\n\n";
  out << "module " << probe_module << ";\n";
  out << "  import \"DPI-C\" function void e1_h1_module_dpi_begin(input string module_name, input string vip_case);\n";
  out << "  import \"DPI-C\" function void e1_h1_module_dpi_cycle(input string module_name, input int cycle, input string phase);\n";
  out << "  import \"DPI-C\" function int e1_h1_module_dpi_compare_u32(\n";
  out << "    input string signal_name,\n";
  out << "    input int cycle,\n";
  out << "    input int imp1_value,\n";
  out << "    input int imp2_value\n";
  out << "  );\n\n";
  out << "  logic clk_i;\n";
  out << "  logic rst_ni;\n\n";
  out << "  e1_h1_imp1_config_sram_ref #(\n";
  out << "    .SIZE_BYTES(" << size_bytes << "),\n";
  out << "    .DATA_WIDTH(" << data_width << "),\n";
  out << "    .BANKS(" << banks << ")\n";
  out << "  ) u_imp1 (\n";
  out << "    .clk_i(clk_i),\n";
  out << "    .rst_ni(rst_ni)\n";
  out << "  );\n\n";
  out << "  e1_h1_config_sram #(\n";
  out << "    .SIZE_BYTES(" << size_bytes << "),\n";
  out << "    .DATA_WIDTH(" << data_width << "),\n";
  out << "    .BANKS(" << banks << ")\n";
  out << "  ) u_imp2 (\n";
  out << "    .clk_i(clk_i),\n";
  out << "    .rst_ni(rst_ni)\n";
  out << "  );\n\n";
  out << "  task automatic tick;\n";
  out << "    clk_i = 1'b0; #1;\n";
  out << "    clk_i = 1'b1; #1;\n";
  out << "  endtask\n\n";
  out << "  task automatic check_initialized(input int cycle);\n";
  out << "    if (e1_h1_module_dpi_compare_u32(\"initialized_q\", cycle, int'({31'd0, u_imp1.initialized_q}), int'({31'd0, u_imp2.initialized_q})) == 0) begin\n";
  out << "      $fatal(1, \"" << module_name << " mismatch initialized_q cycle %0d\", cycle);\n";
  out << "    end\n";
  out << "  endtask\n\n";
  out << "  initial begin\n";
  out << "    e1_h1_module_dpi_begin(\"" << module_name << "\", \"module_only_config_sram\");\n";
  out << "    clk_i = 1'b0;\n";
  out << "    rst_ni = 1'b0;\n";
  out << "    tick();\n";
  out << "    check_initialized(-1);\n";
  out << "    rst_ni = 1'b1;\n";
  out << "    for (int cycle = 0; cycle < 3; cycle++) begin\n";
  out << "      e1_h1_module_dpi_cycle(\"" << module_name << "\", cycle, \"sample_initialized_latch\");\n";
  out << "      tick();\n";
  out << "      check_initialized(cycle);\n";
  out << "    end\n";
  out << "    $finish;\n";
  out << "  end\n";
  out << "endmodule\n\n";
  out << "`default_nettype wire\n";
  return out.str();
}

std::vector<ModuleSpec> module_specs() {
  return {
      {
          "control_cpu",
          "cpu command sequencer",
          "e1_h1_control_cpu",
          "e1_h1_module_dpi_control_cpu",
          "e1/e1-h1/rtl/imp2/e1_h1_control_cpu.sv",
          {"reset_to_first_command", "command_backpressure", "array_completion"},
          {"cycle 0 reset release", "cycle 1 command valid with backpressure", "cycle 5 array completion"},
          false,
          sv_control_cpu(),
      },
      {
          "rgmii_ethernet_ingress",
          "digital RGMII ingress",
          "e1_h1_rgmii_ethernet_ingress",
          "e1_h1_module_dpi_rgmii_ethernet_ingress",
          "e1/e1-h1/rtl/imp2/e1_h1_rgmii_ethernet_ingress.sv",
          {"reset_idle", "minimum_frame", "downstream_backpressure"},
          {"cycle 1 frame starts", "cycles 1-5 nibbles shift", "cycle 7 downstream accepts"},
          false,
          sv_rgmii(),
      },
      {
          "ingress_sram",
          "latched stream buffer",
          "e1_h1_stream_sram",
          "e1_h1_module_dpi_ingress_sram",
          "e1/e1-h1/rtl/imp2/e1_h1_stream_sram.sv",
          {"reset_empty", "single_stream_word", "array_backpressure"},
          {"cycle 0 latch first word", "cycle 1 hold while array_ready_i is low", "cycle 2 release latched word"},
          true,
          sv_stream_sram(),
      },
      {
          "activation_sram",
          "activation storage",
          "e1_h1_config_sram",
          "e1_h1_module_dpi_activation_sram",
          "e1/e1-h1/rtl/imp2/e1_h1_config_sram.sv",
          {"reset_empty", "single_config_read", "parameterized_size"},
          {"cycle -1 reset clears initialized_q", "cycle 0 initialization latch sets", "cycle 1 initialized_q holds"},
          false,
          sv_config_sram("e1_h1_module_dpi_activation_sram", "activation_sram", 524288, 128, 8),
      },
      {
          "accumulator_sram",
          "accumulator storage",
          "e1_h1_config_sram",
          "e1_h1_module_dpi_accumulator_sram",
          "e1/e1-h1/rtl/imp2/e1_h1_config_sram.sv",
          {"reset_empty", "single_config_read", "wide_accumulator_word"},
          {"cycle -1 reset clears initialized_q", "cycle 0 initialization latch sets", "cycle 1 initialized_q holds"},
          false,
          sv_config_sram("e1_h1_module_dpi_accumulator_sram", "accumulator_sram", 524288, 256, 8),
      },
      {
          "systolic_array",
          "array datapath engine",
          "e1_h1_systolic_array",
          "e1_h1_module_dpi_systolic_array",
          "e1/e1-h1/rtl/imp2/e1_h1_systolic_array.sv",
          {"command_acceptance", "input_burst", "completion_pulse"},
          {"cycle 1 command accepted", "cycles 3-6 input burst drains", "cycle 6 completion pulse"},
          false,
          sv_systolic_array(),
      },
  };
}

fs::path parse_path_arg(int argc, char** argv, const std::string& flag, const fs::path& default_value) {
  for (int i = 1; i + 1 < argc; ++i) {
    if (argv[i] == flag) {
      return fs::path(argv[i + 1]);
    }
  }
  return default_value;
}

}  // namespace

int main(int argc, char** argv) {
  try {
    const fs::path repo_root = parse_path_arg(argc, argv, "--repo-root", fs::current_path());
    const fs::path output_dir = parse_path_arg(
        argc,
        argv,
        "--output-dir",
        repo_root / "e1/e1-h1/generated/module_dpi");
    const fs::path rel_output_dir = fs::relative(output_dir, repo_root);
    const fs::path flist_dir = output_dir / "flists";
    const std::vector<ModuleSpec> specs = module_specs();

    for (const ModuleSpec& spec : specs) {
      validate_manifest_inputs(repo_root, spec);
      validate_isolation(repo_root, spec);
      validate_cycle_contract(spec);
    }

    write_text(output_dir / "e1_h1_module_dpi_scoreboard.cpp", scoreboard_cpp());
    for (const ModuleSpec& spec : specs) {
      const fs::path probe_path = rel_output_dir / (spec.probe_module + ".sv");
      write_text(output_dir / (spec.probe_module + ".sv"), spec.probe_sv);
      write_text(output_dir / (spec.probe_module + "_main.cpp"), main_cpp(spec));
      write_text(flist_dir / (spec.name + ".f"), flist_text(probe_path, spec));
    }
    write_text(output_dir / "manifest.json", manifest_json(specs));
    write_text(output_dir / "module_isolation.json", module_isolation_json(specs));
    write_text(output_dir / "cycle_contract.json", cycle_contract_json(specs));
    write_text(output_dir / "module_test_plan.json", module_test_plan_json(specs));

    std::cout << "PASS e1_h1_generate_module_dpi " << specs.size()
              << " modules -> " << output_dir.generic_string() << "\n";
    return 0;
  } catch (const std::exception& ex) {
    std::cerr << "FAIL e1_h1_generate_module_dpi " << ex.what() << "\n";
    return 1;
  }
}
