// SPDX-License-Identifier: Apache-2.0
// Generate per-module DPI probes for generated full-checkpoint RTL modules.

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

struct ModuleSpec {
  std::string name;
  std::string top_module;
  std::string probe_module;
  std::vector<std::string> rtl;
  std::vector<std::string> cycle_notes;
  std::string probe_sv;
};

std::string read_text(const fs::path& path) {
  std::ifstream input(path);
  if (!input) {
    throw std::runtime_error("cannot read " + path.string());
  }
  std::ostringstream buffer;
  buffer << input.rdbuf();
  return buffer.str();
}

void write_text(const fs::path& path, const std::string& text) {
  fs::create_directories(path.parent_path());
  std::ofstream output(path);
  if (!output) {
    throw std::runtime_error("cannot write " + path.string());
  }
  output << text;
}

void validate_rtl_inputs(const fs::path& repo_root, const ModuleSpec& spec) {
  for (const std::string& rtl : spec.rtl) {
    const fs::path rtl_path = repo_root / rtl;
    const std::string text = read_text(rtl_path);
    if (text.find("module " + spec.top_module) == std::string::npos &&
        rtl == spec.rtl.back()) {
      throw std::runtime_error(rtl + " does not define " + spec.top_module);
    }
  }
}

std::string scoreboard_cpp() {
  return R"cpp(// SPDX-License-Identifier: Apache-2.0
// Generated by e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp.

#include <cstdio>

extern "C" void e1_h1_full_dpi_begin(const char* module_name, const char* vip_case) {
  std::printf("E1_H1_FULL_MODULE_DPI_BEGIN module=%s case=%s\n", module_name, vip_case);
}

extern "C" void e1_h1_full_dpi_cycle(const char* module_name, int cycle, const char* phase) {
  if (cycle < 4 || (cycle % 256) == 0) {
    std::printf("E1_H1_FULL_MODULE_DPI_CYCLE module=%s cycle=%d phase=%s\n", module_name, cycle, phase);
  }
}

extern "C" int e1_h1_full_dpi_expect_u32(
    const char* module_name,
    const char* signal_name,
    int cycle,
    int expected,
    int actual) {
  if (expected != actual) {
    std::fprintf(
        stderr,
        "E1_H1_FULL_MODULE_DPI_MISMATCH module=%s signal=%s cycle=%d expected=0x%x actual=0x%x\n",
        module_name,
        signal_name,
        cycle,
        static_cast<unsigned>(expected),
        static_cast<unsigned>(actual));
    return 0;
  }
  return 1;
}
)cpp";
}

std::string main_cpp(const ModuleSpec& spec) {
  std::ostringstream out;
  out << "// SPDX-License-Identifier: Apache-2.0\n";
  out << "// Generated by e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp.\n\n";
  out << "#include \"V" << spec.probe_module << ".h\"\n";
  out << "#include \"verilated.h\"\n\n";
  out << "int main(int argc, char** argv) {\n";
  out << "  VerilatedContext context;\n";
  out << "  context.commandArgs(argc, argv);\n";
  out << "  V" << spec.probe_module << " top{&context};\n";
  out << "  while (!context.gotFinish() && context.time() < 200000) {\n";
  out << "    top.eval();\n";
  out << "    context.timeInc(1);\n";
  out << "  }\n";
  out << "  return context.gotFinish() ? 0 : 1;\n";
  out << "}\n";
  return out.str();
}

std::string flist_text(const fs::path& probe, const ModuleSpec& spec) {
  std::ostringstream out;
  for (const std::string& rtl : spec.rtl) {
    out << rtl << "\n";
  }
  out << probe.generic_string() << "\n";
  return out.str();
}

std::string manifest_json(const std::vector<ModuleSpec>& specs) {
  std::ostringstream out;
  out << "{\n";
  out << "  \"schema\": \"e1-h1-full-checkpoint-generated-module-dpi-v0\",\n";
  out << "  \"generator\": \"e1/e1-h1/tools/generate_full_checkpoint_module_dpi.cpp\",\n";
  out << "  \"scoreboard\": \"e1/e1-h1/generated/full_checkpoint_dpi/e1_h1_full_checkpoint_module_dpi_scoreboard.cpp\",\n";
  out << "  \"construction_rule\": \"one_generated_probe_per_full_checkpoint_rtl_module_with_cpp_dpi_driven_neighbors\",\n";
  out << "  \"modules\": [\n";
  for (std::size_t i = 0; i < specs.size(); ++i) {
    const ModuleSpec& spec = specs[i];
    out << "    {\n";
    out << "      \"name\": \"" << spec.name << "\",\n";
    out << "      \"top_module\": \"" << spec.top_module << "\",\n";
    out << "      \"probe_module\": \"" << spec.probe_module << "\",\n";
    out << "      \"scope\": \"generated_full_checkpoint_module_only\",\n";
    out << "      \"neighbors\": \"cpp_dpi_environment_or_declared_flist_dependencies\",\n";
    out << "      \"probe\": \"e1/e1-h1/generated/full_checkpoint_dpi/" << spec.probe_module << ".sv\",\n";
    out << "      \"main\": \"e1/e1-h1/generated/full_checkpoint_dpi/" << spec.probe_module << "_main.cpp\",\n";
    out << "      \"flist\": \"e1/e1-h1/generated/full_checkpoint_dpi/flists/" << spec.name << ".f\",\n";
    out << "      \"rtl\": [";
    for (std::size_t j = 0; j < spec.rtl.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "\"" << spec.rtl[j] << "\"";
    }
    out << "],\n";
    out << "      \"cycle_notes\": [";
    for (std::size_t j = 0; j < spec.cycle_notes.size(); ++j) {
      out << (j == 0 ? "" : ", ") << "\"" << spec.cycle_notes[j] << "\"";
    }
    out << "]\n";
    out << "    }" << (i + 1 == specs.size() ? "\n" : ",\n");
  }
  out << "  ]\n";
  out << "}\n";
  return out.str();
}

std::string probe_header(const std::string& module_name) {
  std::ostringstream out;
  out << "`default_nettype none\n\n";
  out << "module e1_h1_full_checkpoint_module_dpi_" << module_name << ";\n";
  out << "  import \"DPI-C\" function void e1_h1_full_dpi_begin(input string module_name, input string vip_case);\n";
  out << "  import \"DPI-C\" function void e1_h1_full_dpi_cycle(input string module_name, input int cycle, input string phase);\n";
  out << "  import \"DPI-C\" function int e1_h1_full_dpi_expect_u32(\n";
  out << "    input string module_name,\n";
  out << "    input string signal_name,\n";
  out << "    input int cycle,\n";
  out << "    input int expected,\n";
  out << "    input int actual\n";
  out << "  );\n\n";
  out << "  task automatic tick;\n";
  out << "    clk_i = 1'b0; #1;\n";
  out << "    clk_i = 1'b1; #1;\n";
  out << "  endtask\n\n";
  out << "  task automatic expect_u32(input string signal_name, input int cycle, input int expected, input logic [31:0] actual);\n";
  out << "    if (e1_h1_full_dpi_expect_u32(\"" << module_name << "\", signal_name, cycle, expected, int'(actual)) == 0) begin\n";
  out << "      $fatal(1, \"" << module_name << " mismatch %s\", signal_name);\n";
  out << "    end\n";
  out << "  endtask\n\n";
  return out.str();
}

std::string probe_footer() {
  return "endmodule\n\n`default_nettype wire\n";
}

std::string sv_graph_sequencer() {
  std::ostringstream out;
  out << probe_header("graph_sequencer");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic busy_o;
  logic done_o;
  logic slot_valid_o;
  logic slot_ready_i;
  logic launch_control_o;
  logic launch_linear_o;
  logic op_done_i;
  logic [31:0] layer_o;
  logic [3:0] layer_slot_o;
  logic [2:0] linear_op_index_o;
  logic [2:0] control_op_index_o;
  logic [3:0] control_kind_o;
  logic [31:0] linear_tile_count_o;
  logic [31:0] issued_graph_slots_o;
  logic [1:0] cycle_phase_o;

  e1_h1_tinyllama_graph_sequencer u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .slot_valid_o(slot_valid_o),
    .slot_ready_i(slot_ready_i),
    .launch_control_o(launch_control_o),
    .launch_linear_o(launch_linear_o),
    .op_done_i(op_done_i),
    .layer_o(layer_o),
    .layer_slot_o(layer_slot_o),
    .linear_op_index_o(linear_op_index_o),
    .control_op_index_o(control_op_index_o),
    .control_kind_o(control_kind_o),
    .linear_tile_count_o(linear_tile_count_o),
    .issued_graph_slots_o(issued_graph_slots_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    int linear_launches;
    int control_launches;
    e1_h1_full_dpi_begin("graph_sequencer", "ordered_308_slot_graph");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    slot_ready_i = 1'b1;
    op_done_i = 1'b0;
    linear_launches = 0;
    control_launches = 0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 1600 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("graph_sequencer", cycle, "drive_ready_and_engine_done");
      op_done_i = (cycle_phase_o == 2'd2);
      if (launch_linear_o) linear_launches++;
      if (launch_control_o) control_launches++;
      tick();
    end
    expect_u32("issued_graph_slots_o", 0, 308, issued_graph_slots_o);
    expect_u32("linear_launches", 0, 154, linear_launches[31:0]);
    expect_u32("control_launches", 0, 154, control_launches[31:0]);
    if (!done_o) $fatal(1, "graph sequencer did not finish");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_control_slot_engine() {
  std::ostringstream out;
  out << probe_header("control_slot_engine");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic [31:0] layer_i;
  logic [2:0] control_op_index_i;
  logic [3:0] control_kind_i;
  logic busy_o;
  logic done_o;
  logic control_valid_o;
  logic control_ready_i;
  logic control_commit_o;
  logic [31:0] layer_o;
  logic [2:0] control_op_index_o;
  logic [3:0] control_kind_o;
  logic [31:0] issued_control_ops_o;
  logic [1:0] cycle_phase_o;

  e1_h1_tinyllama_control_slot_engine u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .layer_i(layer_i),
    .control_op_index_i(control_op_index_i),
    .control_kind_i(control_kind_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .control_valid_o(control_valid_o),
    .control_ready_i(control_ready_i),
    .control_commit_o(control_commit_o),
    .layer_o(layer_o),
    .control_op_index_o(control_op_index_o),
    .control_kind_o(control_kind_o),
    .issued_control_ops_o(issued_control_ops_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    e1_h1_full_dpi_begin("control_slot_engine", "single_control_slot");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    layer_i = 32'd3;
    control_op_index_i = 3'd2;
    control_kind_i = 4'd3;
    control_ready_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 16 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("control_slot_engine", cycle, "single_slot_cpu_control");
      control_ready_i = (cycle >= 1);
      tick();
    end
    expect_u32("issued_control_ops_o", 0, 1, issued_control_ops_o);
    expect_u32("layer_o", 0, 3, layer_o);
    expect_u32("control_op_index_o", 0, 2, {29'd0, control_op_index_o});
    expect_u32("control_kind_o", 0, 3, {28'd0, control_kind_o});
    if (!done_o) $fatal(1, "control slot engine did not finish");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_control_scheduler() {
  std::ostringstream out;
  out << probe_header("control_scheduler");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic busy_o;
  logic done_o;
  logic control_valid_o;
  logic control_ready_i;
  logic control_commit_o;
  logic [31:0] layer_o;
  logic [2:0] control_op_index_o;
  logic [3:0] layer_op_slot_o;
  logic [3:0] control_kind_o;
  logic [31:0] issued_control_ops_o;
  logic [1:0] cycle_phase_o;

  e1_h1_tinyllama_control_scheduler u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .control_valid_o(control_valid_o),
    .control_ready_i(control_ready_i),
    .control_commit_o(control_commit_o),
    .layer_o(layer_o),
    .control_op_index_o(control_op_index_o),
    .layer_op_slot_o(layer_op_slot_o),
    .control_kind_o(control_kind_o),
    .issued_control_ops_o(issued_control_ops_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    e1_h1_full_dpi_begin("control_scheduler", "all_154_control_ops");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    control_ready_i = 1'b1;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 900 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("control_scheduler", cycle, "issue_execute_commit_control");
      tick();
    end
    expect_u32("issued_control_ops_o", 0, 154, issued_control_ops_o);
    if (!done_o) $fatal(1, "control scheduler did not finish");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_linear_scheduler() {
  std::ostringstream out;
  out << probe_header("linear_scheduler");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic cmd_valid_o;
  logic cmd_ready_i;
  logic [31:0] cmd_input_addr_o;
  logic [31:0] cmd_weight_addr_o;
  logic [31:0] cmd_output_addr_o;
  logic [15:0] cmd_rows_o;
  logic [15:0] cmd_cols_o;
  logic [15:0] cmd_depth_o;
  logic array_done_i;
  logic array_error_i;
  logic [31:0] layer_o;
  logic [2:0] op_index_o;
  logic [8:0] input_tile_o;
  logic [8:0] output_tile_o;
  logic [31:0] issued_commands_o;
  logic [2:0] cycle_phase_o;

  e1_h1_tinyllama_linear_scheduler u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .cmd_valid_o(cmd_valid_o),
    .cmd_ready_i(cmd_ready_i),
    .cmd_input_addr_o(cmd_input_addr_o),
    .cmd_weight_addr_o(cmd_weight_addr_o),
    .cmd_output_addr_o(cmd_output_addr_o),
    .cmd_rows_o(cmd_rows_o),
    .cmd_cols_o(cmd_cols_o),
    .cmd_depth_o(cmd_depth_o),
    .array_done_i(array_done_i),
    .array_error_i(array_error_i),
    .layer_o(layer_o),
    .op_index_o(op_index_o),
    .input_tile_o(input_tile_o),
    .output_tile_o(output_tile_o),
    .issued_commands_o(issued_commands_o),
    .cycle_phase_o(cycle_phase_o)
  );

  initial begin
    e1_h1_full_dpi_begin("linear_scheduler", "first_four_tile_commands");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    cmd_ready_i = 1'b1;
    array_done_i = 1'b0;
    array_error_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    tick();
    start_i = 1'b0;
    for (int cycle = 0; cycle < 128 && issued_commands_o < 32'd4; cycle++) begin
      e1_h1_full_dpi_cycle("linear_scheduler", cycle, "cpu_tile_command_template");
      array_done_i = (cycle_phase_o == 3'd6);
      tick();
      array_done_i = 1'b0;
    end
    expect_u32("issued_commands_o", 0, 4, issued_commands_o);
    expect_u32("cmd_rows_o", 0, 16, {16'd0, cmd_rows_o});
    expect_u32("cmd_cols_o", 0, 16, {16'd0, cmd_cols_o});
    expect_u32("cmd_depth_o", 0, 16, {16'd0, cmd_depth_o});
    if (error_o) $fatal(1, "linear scheduler reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_linear_tile_engine() {
  std::ostringstream out;
  out << probe_header("linear_tile_engine");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic stream_valid_i;
  logic stream_ready_o;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic [31:0] issued_commands_o;
  logic [2:0] cycle_phase_o;
  logic [31:0] layer_o;
  logic [2:0] op_index_o;
  logic [8:0] input_tile_o;
  logic [8:0] output_tile_o;
  logic scheduler_cmd_valid_o;
  logic array_cmd_valid_o;
  logic array_cmd_ready_o;
  logic [31:0] cmd_input_addr_o;
  logic [31:0] cmd_weight_addr_o;
  logic [31:0] cmd_output_addr_o;
  logic [15:0] cmd_rows_o;
  logic [15:0] cmd_cols_o;
  logic [15:0] cmd_depth_o;
  logic buffer_array_valid_o;
  logic buffer_array_ready_o;
  logic [63:0] buffer_array_data_o;
  logic array_done_o;
  logic array_debug_busy_o;

  e1_h1_tinyllama_linear_tile_engine u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_o),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .issued_commands_o(issued_commands_o),
    .cycle_phase_o(cycle_phase_o),
    .layer_o(layer_o),
    .op_index_o(op_index_o),
    .input_tile_o(input_tile_o),
    .output_tile_o(output_tile_o),
    .scheduler_cmd_valid_o(scheduler_cmd_valid_o),
    .array_cmd_valid_o(array_cmd_valid_o),
    .array_cmd_ready_o(array_cmd_ready_o),
    .cmd_input_addr_o(cmd_input_addr_o),
    .cmd_weight_addr_o(cmd_weight_addr_o),
    .cmd_output_addr_o(cmd_output_addr_o),
    .cmd_rows_o(cmd_rows_o),
    .cmd_cols_o(cmd_cols_o),
    .cmd_depth_o(cmd_depth_o),
    .buffer_array_valid_o(buffer_array_valid_o),
    .buffer_array_ready_o(buffer_array_ready_o),
    .buffer_array_data_o(buffer_array_data_o),
    .array_done_o(array_done_o),
    .array_debug_busy_o(array_debug_busy_o)
  );

  initial begin
    e1_h1_full_dpi_begin("linear_tile_engine", "first_four_composed_tile_commands");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    for (int cycle = 0; cycle < 256 && issued_commands_o < 32'd4; cycle++) begin
      e1_h1_full_dpi_cycle("linear_tile_engine", cycle, "scheduler_latch_array_composition");
      stream_valid_i = 1'b1;
      stream_data_i = 64'h3000 + cycle[15:0];
      tick();
      start_i = 1'b0;
    end
    expect_u32("issued_commands_o", 0, 4, issued_commands_o);
    if (error_o) $fatal(1, "linear tile engine reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_linear_slot_engine() {
  std::ostringstream out;
  out << probe_header("linear_slot_engine");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic [31:0] layer_i;
  logic [2:0] op_index_i;
  logic stream_valid_i;
  logic stream_ready_o;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic [31:0] issued_commands_o;
  logic [31:0] expected_commands_o;
  logic [2:0] cycle_phase_o;
  logic [31:0] layer_o;
  logic [2:0] op_index_o;
  logic [8:0] input_tile_o;
  logic [8:0] output_tile_o;
  logic scheduler_cmd_valid_o;
  logic array_cmd_valid_o;
  logic array_cmd_ready_o;
  logic [31:0] cmd_input_addr_o;
  logic [31:0] cmd_weight_addr_o;
  logic [31:0] cmd_output_addr_o;
  logic [15:0] cmd_rows_o;
  logic [15:0] cmd_cols_o;
  logic [15:0] cmd_depth_o;
  logic buffer_array_valid_o;
  logic buffer_array_ready_o;
  logic [63:0] buffer_array_data_o;
  logic array_done_o;
  logic array_debug_busy_o;

  e1_h1_tinyllama_linear_slot_engine #(
    .SmokeMaxTilesPerLinearSlot(2)
  ) u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .layer_i(layer_i),
    .op_index_i(op_index_i),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_o),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .issued_commands_o(issued_commands_o),
    .expected_commands_o(expected_commands_o),
    .cycle_phase_o(cycle_phase_o),
    .layer_o(layer_o),
    .op_index_o(op_index_o),
    .input_tile_o(input_tile_o),
    .output_tile_o(output_tile_o),
    .scheduler_cmd_valid_o(scheduler_cmd_valid_o),
    .array_cmd_valid_o(array_cmd_valid_o),
    .array_cmd_ready_o(array_cmd_ready_o),
    .cmd_input_addr_o(cmd_input_addr_o),
    .cmd_weight_addr_o(cmd_weight_addr_o),
    .cmd_output_addr_o(cmd_output_addr_o),
    .cmd_rows_o(cmd_rows_o),
    .cmd_cols_o(cmd_cols_o),
    .cmd_depth_o(cmd_depth_o),
    .buffer_array_valid_o(buffer_array_valid_o),
    .buffer_array_ready_o(buffer_array_ready_o),
    .buffer_array_data_o(buffer_array_data_o),
    .array_done_o(array_done_o),
    .array_debug_busy_o(array_debug_busy_o)
  );

  initial begin
    e1_h1_full_dpi_begin("linear_slot_engine", "bounded_two_tile_linear_slot");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    layer_i = 32'd0;
    op_index_i = 3'd0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    for (int cycle = 0; cycle < 128 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("linear_slot_engine", cycle, "slot_local_scheduler_latch_array");
      stream_valid_i = 1'b1;
      stream_data_i = 64'h4000 + cycle[15:0];
      tick();
      start_i = 1'b0;
    end
    expect_u32("issued_commands_o", 0, 2, issued_commands_o);
    expect_u32("expected_commands_o", 0, 2, expected_commands_o);
    if (!done_o) $fatal(1, "linear slot engine did not finish");
    if (error_o) $fatal(1, "linear slot engine reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::string sv_full_top() {
  std::ostringstream out;
  out << probe_header("full_checkpoint_top");
  out << R"sv(  logic clk_i;
  logic rst_ni;
  logic start_i;
  logic stream_valid_i;
  logic stream_ready_o;
  logic [63:0] stream_data_i;
  logic stream_last_i;
  logic stream_error_i;
  logic busy_o;
  logic done_o;
  logic error_o;
  logic [31:0] issued_graph_slots_o;
  logic [31:0] issued_linear_commands_o;
  logic [31:0] issued_control_ops_o;
  logic [31:0] active_layer_o;
  logic [3:0] active_slot_o;
  logic [1:0] graph_cycle_phase_o;
  logic [2:0] linear_cycle_phase_o;
  logic [1:0] control_cycle_phase_o;
  logic launch_linear_o;
  logic launch_control_o;
  logic linear_busy_o;
  logic control_busy_o;
  logic buffer_array_valid_o;
  logic buffer_array_ready_o;
  logic array_done_o;
  logic array_debug_busy_o;

  e1_h1_tinyllama_full_checkpoint_top #(
    .SmokeMaxTilesPerLinearSlot(1)
  ) u_dut (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .start_i(start_i),
    .stream_valid_i(stream_valid_i),
    .stream_ready_o(stream_ready_o),
    .stream_data_i(stream_data_i),
    .stream_last_i(stream_last_i),
    .stream_error_i(stream_error_i),
    .busy_o(busy_o),
    .done_o(done_o),
    .error_o(error_o),
    .issued_graph_slots_o(issued_graph_slots_o),
    .issued_linear_commands_o(issued_linear_commands_o),
    .issued_control_ops_o(issued_control_ops_o),
    .active_layer_o(active_layer_o),
    .active_slot_o(active_slot_o),
    .graph_cycle_phase_o(graph_cycle_phase_o),
    .linear_cycle_phase_o(linear_cycle_phase_o),
    .control_cycle_phase_o(control_cycle_phase_o),
    .launch_linear_o(launch_linear_o),
    .launch_control_o(launch_control_o),
    .linear_busy_o(linear_busy_o),
    .control_busy_o(control_busy_o),
    .buffer_array_valid_o(buffer_array_valid_o),
    .buffer_array_ready_o(buffer_array_ready_o),
    .array_done_o(array_done_o),
    .array_debug_busy_o(array_debug_busy_o)
  );

  initial begin
    int linear_launches;
    int control_launches;
    e1_h1_full_dpi_begin("full_checkpoint_top", "bounded_all_308_graph_slots");
    clk_i = 1'b0;
    rst_ni = 1'b0;
    start_i = 1'b0;
    stream_valid_i = 1'b0;
    stream_data_i = 64'd0;
    stream_last_i = 1'b0;
    stream_error_i = 1'b0;
    linear_launches = 0;
    control_launches = 0;
    tick();
    tick();
    rst_ni = 1'b1;
    start_i = 1'b1;
    for (int cycle = 0; cycle < 10000 && !done_o; cycle++) begin
      e1_h1_full_dpi_cycle("full_checkpoint_top", cycle, "graph_dispatch_to_slot_engines");
      stream_valid_i = 1'b1;
      stream_data_i = 64'h5000 + cycle[15:0];
      if (launch_linear_o) linear_launches++;
      if (launch_control_o) control_launches++;
      tick();
      start_i = 1'b0;
    end
    expect_u32("issued_graph_slots_o", 0, 308, issued_graph_slots_o);
    expect_u32("issued_linear_commands_o", 0, 154, issued_linear_commands_o);
    expect_u32("issued_control_ops_o", 0, 154, issued_control_ops_o);
    expect_u32("linear_launches", 0, 154, linear_launches[31:0]);
    expect_u32("control_launches", 0, 154, control_launches[31:0]);
    if (!done_o) $fatal(1, "full checkpoint top did not finish");
    if (error_o) $fatal(1, "full checkpoint top reported error");
    $finish;
  end
)sv";
  out << probe_footer();
  return out.str();
}

std::vector<ModuleSpec> module_specs() {
  const std::string gen = "e1/e1-h1/generated/full_checkpoint/";
  const std::string stream = "e1/e1-h1/rtl/imp2/e1_h1_stream_sram.sv";
  const std::string array = "e1/e1-h1/rtl/imp2/e1_h1_systolic_array.sv";
  return {
      {
          "linear_scheduler",
          "e1_h1_tinyllama_linear_scheduler",
          "e1_h1_full_checkpoint_module_dpi_linear_scheduler",
          {gen + "e1_h1_tinyllama_linear_scheduler.sv"},
          {"cycle 0 setup", "cycle 2 command handshake", "cycle 6 array done"},
          sv_linear_scheduler(),
      },
      {
          "linear_tile_engine",
          "e1_h1_tinyllama_linear_tile_engine",
          "e1_h1_full_checkpoint_module_dpi_linear_tile_engine",
          {gen + "e1_h1_tinyllama_linear_scheduler.sv", stream, array, gen + "e1_h1_tinyllama_linear_tile_engine.sv"},
          {"cycle 1 scheduler valid", "cycle 2 gated array command", "cycles 3-6 latch/array transfer"},
          sv_linear_tile_engine(),
      },
      {
          "control_scheduler",
          "e1_h1_tinyllama_control_scheduler",
          "e1_h1_full_checkpoint_module_dpi_control_scheduler",
          {gen + "e1_h1_tinyllama_control_scheduler.sv"},
          {"cycle 0 control issue", "cycle 2 execute", "cycle 3 commit"},
          sv_control_scheduler(),
      },
      {
          "graph_sequencer",
          "e1_h1_tinyllama_graph_sequencer",
          "e1_h1_full_checkpoint_module_dpi_graph_sequencer",
          {gen + "e1_h1_tinyllama_graph_sequencer.sv"},
          {"cycle 0 present graph slot", "cycle 1 launch selected engine", "cycle 2 wait done", "cycle 3 commit"},
          sv_graph_sequencer(),
      },
      {
          "linear_slot_engine",
          "e1_h1_tinyllama_linear_slot_engine",
          "e1_h1_full_checkpoint_module_dpi_linear_slot_engine",
          {stream, array, gen + "e1_h1_tinyllama_linear_slot_engine.sv"},
          {"cycle 1 slot command valid", "cycle 2 array command", "cycles 3-6 separated latch/array"},
          sv_linear_slot_engine(),
      },
      {
          "control_slot_engine",
          "e1_h1_tinyllama_control_slot_engine",
          "e1_h1_full_checkpoint_module_dpi_control_slot_engine",
          {gen + "e1_h1_tinyllama_control_slot_engine.sv"},
          {"cycle 0 control valid", "cycle 2 execute", "cycle 3 commit"},
          sv_control_slot_engine(),
      },
      {
          "full_checkpoint_top",
          "e1_h1_tinyllama_full_checkpoint_top",
          "e1_h1_full_checkpoint_module_dpi_full_checkpoint_top",
          {
              gen + "e1_h1_tinyllama_graph_sequencer.sv",
              stream,
              array,
              gen + "e1_h1_tinyllama_linear_slot_engine.sv",
              gen + "e1_h1_tinyllama_control_slot_engine.sv",
              gen + "e1_h1_tinyllama_full_checkpoint_top.sv",
          },
          {"cycle 0 graph slot", "cycle 1 slot start", "cycle 2 selected engine runs", "cycle 3 graph commit"},
          sv_full_top(),
      },
  };
}

fs::path parse_path_arg(int argc, char** argv, const std::string& flag, const fs::path& default_value) {
  for (int i = 1; i + 1 < argc; ++i) {
    if (argv[i] == flag) {
      return fs::path(argv[i + 1]);
    }
  }
  return default_value;
}

}  // namespace

int main(int argc, char** argv) {
  try {
    const fs::path repo_root = parse_path_arg(argc, argv, "--repo-root", fs::current_path());
    const fs::path output_dir = parse_path_arg(
        argc,
        argv,
        "--output-dir",
        repo_root / "e1/e1-h1/generated/full_checkpoint_dpi");
    const fs::path rel_output_dir = fs::relative(output_dir, repo_root);
    const fs::path flist_dir = output_dir / "flists";
    const std::vector<ModuleSpec> specs = module_specs();

    for (const ModuleSpec& spec : specs) {
      validate_rtl_inputs(repo_root, spec);
    }

    write_text(output_dir / "e1_h1_full_checkpoint_module_dpi_scoreboard.cpp", scoreboard_cpp());
    for (const ModuleSpec& spec : specs) {
      const fs::path probe_path = rel_output_dir / (spec.probe_module + ".sv");
      write_text(output_dir / (spec.probe_module + ".sv"), spec.probe_sv);
      write_text(output_dir / (spec.probe_module + "_main.cpp"), main_cpp(spec));
      write_text(flist_dir / (spec.name + ".f"), flist_text(probe_path, spec));
    }
    write_text(output_dir / "manifest.json", manifest_json(specs));

    std::cout << "PASS e1_h1_generate_full_checkpoint_module_dpi " << specs.size()
              << " modules -> " << output_dir.generic_string() << "\n";
    return 0;
  } catch (const std::exception& ex) {
    std::cerr << "FAIL e1_h1_generate_full_checkpoint_module_dpi " << ex.what() << "\n";
    return 1;
  }
}
