#!/usr/bin/env python3
"""Generate the E1-H1 SoC top from IP manifests."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class Port:
    instance: str
    module: str
    name: str
    direction: str
    width: int
    connect: str


@dataclass(frozen=True)
class Ip:
    name: str
    module: str
    order: int
    description: str
    parameters: dict[str, int]
    ports: list[Port]


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_ips(ip_dir: Path) -> list[Ip]:
    ips: list[Ip] = []
    for path in sorted(ip_dir.glob("*.json")):
        data = load_json(path)
        if data.get("schema") != "e1-h1-ip-v0":
            raise ValueError(f"{path}: unsupported schema {data.get('schema')!r}")
        name = data["name"]
        module = data["module"]
        ports = [
            Port(
                instance=name,
                module=module,
                name=port["name"],
                direction=port["direction"],
                width=int(port["width"]),
                connect=port["connect"],
            )
            for port in data["ports"]
        ]
        ips.append(
            Ip(
                name=name,
                module=module,
                order=int(data["order"]),
                description=data.get("description", ""),
                parameters={k: int(v) for k, v in data.get("parameters", {}).items()},
                ports=ports,
            )
        )
    return sorted(ips, key=lambda ip: (ip.order, ip.name))


def sv_width(width: int) -> str:
    if width == 1:
        return ""
    return f"[{width - 1}:0] "


def signal_name(connect: str) -> str:
    prefix, name = connect.split(".", 1)
    if prefix not in {"top", "net"}:
        raise ValueError(f"unsupported connection prefix in {connect!r}")
    return name


def collect_top_ports(ips: list[Ip]) -> dict[str, tuple[str, int]]:
    top_ports: dict[str, tuple[str, int]] = {}
    for ip in ips:
        for port in ip.ports:
            if not port.connect.startswith("top."):
                continue
            name = signal_name(port.connect)
            existing = top_ports.get(name)
            value = (port.direction, port.width)
            if existing is not None and existing != value:
                raise ValueError(f"conflicting top port {name}: {existing} vs {value}")
            top_ports[name] = value
    return top_ports


def collect_nets(ips: list[Ip]) -> dict[str, int]:
    nets: dict[str, int] = {}
    for ip in ips:
        for port in ip.ports:
            if not port.connect.startswith("net."):
                continue
            name = signal_name(port.connect)
            existing = nets.get(name)
            if existing is not None and existing != port.width:
                raise ValueError(f"conflicting net {name}: {existing} vs {port.width}")
            nets[name] = port.width
    return nets


def emit_instance(ip: Ip) -> list[str]:
    lines: list[str] = []
    if ip.description:
        lines.append(f"  // {ip.description}")
    if ip.parameters:
        lines.append(f"  {ip.module} #(")
        params = list(ip.parameters.items())
        for index, (name, value) in enumerate(params):
            comma = "," if index < len(params) - 1 else ""
            lines.append(f"    .{name}({value}){comma}")
        lines.append(f"  ) u_{ip.name} (")
    else:
        lines.append(f"  {ip.module} u_{ip.name} (")
    for index, port in enumerate(ip.ports):
        comma = "," if index < len(ip.ports) - 1 else ""
        lines.append(f"    .{port.name}({signal_name(port.connect)}){comma}")
    lines.append("  );")
    lines.append("")
    return lines


def generate(architecture_path: Path, ip_dir: Path) -> str:
    arch = load_json(architecture_path)
    ips = load_ips(ip_dir)
    top_ports = collect_top_ports(ips)
    nets = collect_nets(ips)

    module_name = f"{arch['architecture_id'].replace('-', '_')}_soc_top"
    lines = [
        "// Generated by e1/e1-h1/tools/generate_soc_top.py",
        f"// Example: {arch['example']}",
        f"// Architecture: {arch['architecture_id']}",
        "// Source of composition: e1/e1-h1/ip/*.json",
        "`default_nettype none",
        "",
        f"module {module_name} (",
    ]

    ordered_ports = sorted(top_ports.items())
    for index, (name, (direction, width)) in enumerate(ordered_ports):
        comma = "," if index < len(ordered_ports) - 1 else ""
        lines.append(f"  {direction} logic {sv_width(width)}{name}{comma}")
    lines.append(");")
    lines.append("")

    for name, width in sorted(nets.items()):
        lines.append(f"  logic {sv_width(width)}{name};")
    lines.append("")

    for ip in ips:
        lines.extend(emit_instance(ip))

    lines.append("endmodule")
    lines.append("")
    lines.append("`default_nettype wire")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--architecture", type=Path, required=True)
    parser.add_argument("--ip-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    text = generate(args.architecture, args.ip_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
